# Generated by Django 5.0.6 on 2026-08-28 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_results', '0001_initial'),
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('XRAY', 'X-ray'), ('CT', 'CT'), ('PATHOLOGY', '병리'), ('STAGING', '병기(TNM)'), ('GENE', '유전자'), ('TREATMENT', '치료')], max_length=20)),
                ('result_status', models.CharField(choices=[('DRAFT', '작성중'), ('CONFIRMED', '확정')], default='DRAFT', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_results', to='cases.lungcancercase')),
                ('confirmed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_clinical_results', to=settings.AUTH_USER_MODEL)),
                ('reviewed_ai_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_results', to='ai_results.airesult')),
                ('source_image_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_results', to='cases.caseimageasset')),
            ],
            options={
                'db_table': 'clinical_results',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_name', models.CharField(max_length=200)),
                ('ingredient_name', models.CharField(max_length=200)),
                ('hira_ingredient_code', models.CharField(blank=True, max_length=50, null=True)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('standard_code', models.CharField(blank=True, max_length=50, null=True)),
                ('mfds_item_seq', models.CharField(blank=True, max_length=50, null=True)),
                ('dur_ingredient_code', models.CharField(blank=True, max_length=50, null=True)),
                ('strength', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('strength_unit', models.CharField(blank=True, max_length=30, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=100, null=True)),
                ('route', models.CharField(blank=True, choices=[('ORAL', '경구'), ('INTRAVENOUS', '정맥'), ('INTRAMUSCULAR', '근육'), ('SUBCUTANEOUS', '피하'), ('INHALATION', '흡입'), ('OTHER', '기타')], max_length=15, null=True)),
                ('efficacy_class_code', models.CharField(blank=True, max_length=50, null=True)),
                ('atc_code', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'drugs',
            },
        ),
        migrations.CreateModel(
            name='GeneFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gene_symbol', models.CharField(max_length=30)),
                ('assessment', models.CharField(choices=[('LIKELY_POSITIVE', '양성가능성'), ('LIKELY_NEGATIVE', '음성가능성'), ('INDETERMINATE', '판정불가')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gene_findings',
            },
        ),
        migrations.CreateModel(
            name='Nodule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nodule_no', models.SmallIntegerField()),
                ('tracking_status', models.CharField(choices=[('TRACKING', '추적중'), ('RESOLVED', '해소됨')], default='TRACKING', max_length=10)),
            ],
            options={
                'db_table': 'nodules',
            },
        ),
        migrations.CreateModel(
            name='NoduleObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lobe', models.CharField(blank=True, choices=[('RUL', '우상엽'), ('RML', '우중엽'), ('RLL', '우하엽'), ('LUL', '좌상엽'), ('LLL', '좌하엽'), ('UNKNOWN', '미상')], max_length=10, null=True)),
                ('location_description', models.CharField(blank=True, max_length=255, null=True)),
                ('max_diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('volume_mm3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('surface_area_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sphericity', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('spiculation', models.CharField(blank=True, choices=[('PRESENT', '있음'), ('ABSENT', '없음'), ('INDETERMINATE', '판정불가')], max_length=15, null=True)),
                ('lobulation', models.CharField(blank=True, choices=[('PRESENT', '있음'), ('ABSENT', '없음'), ('INDETERMINATE', '판정불가')], max_length=15, null=True)),
                ('malignancy_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'nodule_observations',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_number', models.SmallIntegerField()),
                ('phase', models.CharField(choices=[('INDUCTION', '초기치료'), ('MAINTENANCE', '유지요법')], max_length=15)),
                ('cycle_start_date', models.DateField()),
                ('prescription_status', models.CharField(choices=[('DRAFT', '작성중'), ('VALIDATED', '검증완료'), ('FINAL', '최종확정'), ('COMPLETED', '완료'), ('CANCELLED', '취소됨')], max_length=15)),
                ('prescribed_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard_dose', models.DecimalField(decimal_places=3, max_digits=12)),
                ('dose_basis', models.CharField(choices=[('FIXED', '고정용량'), ('MG_PER_M2', 'mg/m²'), ('MG_PER_KG', 'mg/kg'), ('AUC', 'AUC'), ('OTHER', '기타')], max_length=10)),
                ('patient_bsa', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('target_auc', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('renal_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('calculated_dose', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('final_dose', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit', models.CharField(max_length=30)),
                ('route', models.CharField(choices=[('ORAL', '경구'), ('INTRAVENOUS', '정맥'), ('INTRAMUSCULAR', '근육'), ('SUBCUTANEOUS', '피하'), ('INHALATION', '흡입'), ('OTHER', '기타')], max_length=15)),
                ('administration_day', models.CharField(max_length=50)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prescription_items',
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regimen_code', models.CharField(max_length=50, unique=True)),
                ('regimen_name', models.CharField(max_length=200)),
                ('cancer_type', models.CharField(max_length=100)),
                ('histology', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment_line', models.CharField(blank=True, max_length=30, null=True)),
                ('cycle_length_days', models.SmallIntegerField()),
                ('induction_cycles', models.SmallIntegerField(blank=True, null=True)),
                ('maintenance_yn', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('source_version', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'regimens',
            },
        ),
        migrations.CreateModel(
            name='RegimenDrug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dose', models.DecimalField(decimal_places=3, max_digits=12)),
                ('dose_basis', models.CharField(choices=[('FIXED', '고정용량'), ('MG_PER_M2', 'mg/m²'), ('MG_PER_KG', 'mg/kg'), ('AUC', 'AUC'), ('OTHER', '기타')], max_length=10)),
                ('route', models.CharField(choices=[('ORAL', '경구'), ('INTRAVENOUS', '정맥'), ('INTRAMUSCULAR', '근육'), ('SUBCUTANEOUS', '피하'), ('INHALATION', '흡입'), ('OTHER', '기타')], max_length=15)),
                ('administration_day', models.CharField(max_length=50)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence', models.SmallIntegerField()),
                ('phase', models.CharField(choices=[('INDUCTION', '초기치료'), ('MAINTENANCE', '유지요법')], max_length=15)),
            ],
            options={
                'db_table': 'regimen_drugs',
            },
        ),
        migrations.CreateModel(
            name='SafetyCheckResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('DRUG_INTERACTION', '약물상호작용'), ('ALLERGY', '알레르기'), ('RENAL_FUNCTION', '신장기능'), ('HEPATIC_FUNCTION', '간기능'), ('DOSE', '용량'), ('AGE', '연령'), ('PREGNANCY', '임신'), ('DUPLICATION', '중복처방')], max_length=20)),
                ('result', models.CharField(choices=[('PASS', '통과'), ('WARNING', '경고'), ('BLOCK', '차단')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('source_code', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'safety_check_results',
            },
        ),
        migrations.CreateModel(
            name='TreatmentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(max_length=50)),
                ('cancer_type', models.CharField(max_length=100)),
                ('histology', models.CharField(blank=True, max_length=100, null=True)),
                ('stage_condition', models.JSONField(blank=True, null=True)),
                ('biomarker_condition', models.JSONField(blank=True, null=True)),
                ('pdl1_condition', models.JSONField(blank=True, null=True)),
                ('ecog_condition', models.JSONField(blank=True, null=True)),
                ('treatment_line', models.CharField(blank=True, max_length=30, null=True)),
                ('priority', models.SmallIntegerField()),
                ('evidence_source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'treatment_rules',
            },
        ),
        migrations.CreateModel(
            name='CaseFinalResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_summary', models.TextField()),
                ('finalized_at', models.DateTimeField()),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='final_result', to='cases.lungcancercase')),
                ('finalized_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalized_case_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_final_results',
            },
        ),
        migrations.CreateModel(
            name='CtResult',
            fields=[
                ('clinical_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ct_detail', serialize=False, to='clinical.clinicalresult')),
                ('overall_assessment', models.CharField(choices=[('NO_NODULE', '결절없음'), ('NODULE_DETECTED', '결절발견'), ('INDETERMINATE', '판정불가')], max_length=20)),
                ('overall_malignancy_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('finding_summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ct_results',
            },
        ),
        migrations.CreateModel(
            name='GeneResult',
            fields=[
                ('clinical_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gene_detail', serialize=False, to='clinical.clinicalresult')),
                ('interpretation', models.TextField(blank=True, null=True)),
                ('additional_test_recommended', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gene_results',
            },
        ),
        migrations.CreateModel(
            name='PathologyResult',
            fields=[
                ('clinical_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pathology_detail', serialize=False, to='clinical.clinicalresult')),
                ('malignancy_status', models.CharField(choices=[('BENIGN', '양성'), ('MALIGNANT', '악성'), ('INDETERMINATE', '판정불가')], max_length=15)),
                ('histologic_type', models.CharField(blank=True, max_length=100, null=True)),
                ('subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis_summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pathology_results',
            },
        ),
        migrations.CreateModel(
            name='SpecimenAdequacyResult',
            fields=[
                ('clinical_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='specimen_adequacy_detail', serialize=False, to='clinical.clinicalresult')),
                ('adequacy_status', models.CharField(choices=[('ADEQUATE', '적정'), ('INADEQUATE', '부적정'), ('INDETERMINATE', '판정불가')], max_length=15)),
                ('tumor_cell_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'specimen_adequacy_results',
            },
        ),
        migrations.CreateModel(
            name='TnmResult',
            fields=[
                ('clinical_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tnm_detail', serialize=False, to='clinical.clinicalresult')),
                ('t_category', models.CharField(max_length=10)),
                ('n_category', models.CharField(max_length=10)),
                ('m_category', models.CharField(max_length=10)),
                ('stage_group', models.CharField(max_length=20)),
                ('evidence', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tnm_results',
            },
        ),
        migrations.CreateModel(
            name='TreatmentDecision',
            fields=[
                ('clinical_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='treatment_detail', serialize=False, to='clinical.clinicalresult')),
                ('ai_recommendation_action', models.CharField(choices=[('ACCEPTED', '수용'), ('MODIFIED', '수정'), ('REJECTED', '거부'), ('NOT_USED', '미사용')], max_length=15)),
                ('treatment_type', models.CharField(choices=[('SURGERY', '수술'), ('RADIATION', '방사선치료'), ('CHEMOTHERAPY', '항암화학요법'), ('TARGETED_THERAPY', '표적치료'), ('IMMUNOTHERAPY', '면역치료'), ('COMBINATION', '병합치료'), ('SUPPORTIVE_CARE', '완화치료'), ('OBSERVATION', '경과관찰'), ('OTHER', '기타')], max_length=20)),
                ('treatment_plan', models.TextField()),
                ('targeted_therapy_plan', models.TextField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'treatment_decisions',
            },
        ),
        migrations.CreateModel(
            name='XrayResult',
            fields=[
                ('clinical_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='xray_detail', serialize=False, to='clinical.clinicalresult')),
                ('assessment', models.CharField(choices=[('NEGATIVE', '음성'), ('SUSPICIOUS', '의심'), ('INDETERMINATE', '판정불가')], max_length=15)),
                ('finding_summary', models.TextField(blank=True, null=True)),
                ('recommended_action', models.CharField(choices=[('NO_FURTHER_ACTION', '추가조치없음'), ('CHEST_CT', '흉부CT권고'), ('REPEAT_XRAY', 'X-ray재검')], max_length=20)),
            ],
            options={
                'db_table': 'xray_results',
            },
        ),
        migrations.AddConstraint(
            model_name='drug',
            constraint=models.CheckConstraint(check=models.Q(('strength__gte', 0)), name='ck_drug_strength_ge0'),
        ),
        migrations.AddField(
            model_name='nodule',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodules', to='cases.lungcancercase'),
        ),
        migrations.AddField(
            model_name='noduleobservation',
            name='nodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='clinical.nodule'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='cases.lungcancercase'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='clinical.drug'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='clinical.prescription'),
        ),
        migrations.AddConstraint(
            model_name='regimen',
            constraint=models.CheckConstraint(check=models.Q(('cycle_length_days__gt', 0)), name='ck_regimen_cycle_len_gt0'),
        ),
        migrations.AddConstraint(
            model_name='regimen',
            constraint=models.CheckConstraint(check=models.Q(('induction_cycles__gte', 0)), name='ck_regimen_induction_ge0'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='regimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinical.regimen'),
        ),
        migrations.AddField(
            model_name='regimendrug',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regimen_drugs', to='clinical.drug'),
        ),
        migrations.AddField(
            model_name='regimendrug',
            name='regimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regimen_drugs', to='clinical.regimen'),
        ),
        migrations.AddField(
            model_name='safetycheckresult',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_check_results', to='clinical.prescription'),
        ),
        migrations.AddField(
            model_name='safetycheckresult',
            name='prescription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safety_check_results', to='clinical.prescriptionitem'),
        ),
        migrations.AddField(
            model_name='treatmentrule',
            name='regimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_rules', to='clinical.regimen'),
        ),
        migrations.AddField(
            model_name='noduleobservation',
            name='ct_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodule_observations', to='clinical.ctresult'),
        ),
        migrations.AddConstraint(
            model_name='ctresult',
            constraint=models.CheckConstraint(check=models.Q(('overall_malignancy_risk__gte', 0), ('overall_malignancy_risk__lte', 100)), name='ck_ct_result_malig_0_100'),
        ),
        migrations.AddField(
            model_name='genefinding',
            name='gene_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_findings', to='clinical.generesult'),
        ),
        migrations.AddConstraint(
            model_name='specimenadequacyresult',
            constraint=models.CheckConstraint(check=models.Q(('tumor_cell_ratio__gte', 0), ('tumor_cell_ratio__lte', 100)), name='ck_spec_result_ratio_0_100'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatment_decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinical.treatmentdecision'),
        ),
        migrations.AddConstraint(
            model_name='nodule',
            constraint=models.UniqueConstraint(fields=('case', 'nodule_no'), name='uq_nodule_case_no'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(check=models.Q(('standard_dose__gte', 0)), name='ck_rxitem_standard_dose_ge0'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(check=models.Q(('patient_bsa__gt', 0)), name='ck_rxitem_bsa_gt0'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(check=models.Q(('target_auc__gt', 0)), name='ck_rxitem_auc_gt0'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(check=models.Q(('renal_value__gte', 0)), name='ck_rxitem_renal_ge0'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(check=models.Q(('calculated_dose__gte', 0)), name='ck_rxitem_calc_dose_ge0'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(check=models.Q(('final_dose__gte', 0)), name='ck_rxitem_final_dose_ge0'),
        ),
        migrations.AddConstraint(
            model_name='regimendrug',
            constraint=models.UniqueConstraint(fields=('regimen', 'drug', 'phase', 'administration_day', 'sequence'), name='uq_regimen_drug_slot'),
        ),
        migrations.AddConstraint(
            model_name='regimendrug',
            constraint=models.CheckConstraint(check=models.Q(('dose__gte', 0)), name='ck_regimendrug_dose_ge0'),
        ),
        migrations.AddConstraint(
            model_name='regimendrug',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='ck_regimendrug_seq_ge1'),
        ),
        migrations.AddConstraint(
            model_name='treatmentrule',
            constraint=models.UniqueConstraint(fields=('rule_code', 'priority'), name='uq_treatmentrule_code_priority'),
        ),
        migrations.AddConstraint(
            model_name='treatmentrule',
            constraint=models.UniqueConstraint(fields=('rule_code', 'regimen'), name='uq_treatmentrule_code_regimen'),
        ),
        migrations.AddConstraint(
            model_name='treatmentrule',
            constraint=models.CheckConstraint(check=models.Q(('priority__gte', 1)), name='ck_treatmentrule_priority_ge1'),
        ),
        migrations.AddConstraint(
            model_name='noduleobservation',
            constraint=models.UniqueConstraint(fields=('nodule', 'ct_result'), name='uq_nodule_obs_nodule_ctresult'),
        ),
        migrations.AddConstraint(
            model_name='noduleobservation',
            constraint=models.CheckConstraint(check=models.Q(('max_diameter_mm__gte', 0)), name='ck_nodobs_diameter_ge0'),
        ),
        migrations.AddConstraint(
            model_name='noduleobservation',
            constraint=models.CheckConstraint(check=models.Q(('volume_mm3__gte', 0)), name='ck_nodobs_volume_ge0'),
        ),
        migrations.AddConstraint(
            model_name='noduleobservation',
            constraint=models.CheckConstraint(check=models.Q(('surface_area_mm2__gte', 0)), name='ck_nodobs_surface_ge0'),
        ),
        migrations.AddConstraint(
            model_name='noduleobservation',
            constraint=models.CheckConstraint(check=models.Q(('sphericity__gte', 0), ('sphericity__lte', 1)), name='ck_nodobs_sphericity_0_1'),
        ),
        migrations.AddConstraint(
            model_name='noduleobservation',
            constraint=models.CheckConstraint(check=models.Q(('malignancy_risk__gte', 0), ('malignancy_risk__lte', 100)), name='ck_nodobs_malig_0_100'),
        ),
        migrations.AddConstraint(
            model_name='genefinding',
            constraint=models.UniqueConstraint(fields=('gene_result', 'gene_symbol'), name='uq_gene_finding_result_symbol'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(check=models.Q(('cycle_number__gte', 1)), name='ck_prescription_cycle_ge1'),
        ),
    ]
