# Generated by Django 5.0.6 on 2026-09-06 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
        ("pathology", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDL1Result",
            fields=[
                (
                    "clinical_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pdl1_detail",
                        serialize=False,
                        to="clinical.clinicalresult",
                    ),
                ),
                (
                    "tps_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("interpretation", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "source_wsi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pdl1_results",
                        to="pathology.wholeslideimage",
                    ),
                ),
            ],
            options={
                "db_table": "pdl1_results",
            },
        ),
        migrations.AddConstraint(
            model_name="pdl1result",
            constraint=models.CheckConstraint(
                check=models.Q(("tps_percent__gte", 0), ("tps_percent__lte", 100)),
                name="ck_pdl1_tps_0_100",
            ),
        ),
    ]
