# Generated by Django 5.0.6 on 2026-09-06 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0002_pdl1result_pdl1result_ck_pdl1_tps_0_100"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentdecision",
            name="selected_regimen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treatment_decisions",
                to="clinical.regimen",
            ),
        ),
    ]
