# Generated by Django 5.0.6 on 2026-09-11 15:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_examination_order(apps, schema_editor):
    ClinicalResult = apps.get_model("clinical", "ClinicalResult")
    updates = []
    queryset = ClinicalResult.objects.select_related(
        "source_image_asset__examination_order",
        "reviewed_ai_result__ai_analysis__examination_order",
    )
    for result in queryset.iterator():
        source_order_id = (
            result.source_image_asset.examination_order_id
            if result.source_image_asset_id
            else None
        )
        analysis_order_id = (
            result.reviewed_ai_result.ai_analysis.examination_order_id
            if result.reviewed_ai_result_id
            else None
        )
        candidates = {value for value in (source_order_id, analysis_order_id) if value}
        if len(candidates) != 1:
            continue
        order_id = candidates.pop()
        order = (
            result.source_image_asset.examination_order
            if source_order_id
            else result.reviewed_ai_result.ai_analysis.examination_order
        )
        if order.case_id != result.case_id:
            continue
        result.examination_order_id = order_id
        updates.append(result)
    if updates:
        ClinicalResult.objects.bulk_update(updates, ["examination_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("ai_results", "0004_aianalysis_examination_order"),
        ("cases", "0003_examinationorder_pathology_test_type"),
        ("clinical", "0004_safetycheckresult_acknowledged_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalresult",
            name="examination_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinical_results",
                to="cases.examinationorder",
            ),
        ),
        migrations.RunPython(backfill_examination_order, migrations.RunPython.noop),
    ]
