# Generated by Django 5.0.6 on 2026-09-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0005_clinicalresult_examination_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="regimendrug",
            name="dose_unit",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
