# Generated by Django 5.0.6 on 2026-09-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0007_regimendrug_result_unit_alter_prescription_phase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genefinding",
            name="alteration_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
