# Generated by Django 5.0.6 on 2026-09-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0008_genefinding_alteration_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="renal_value_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
