# Generated by Django 5.0.6 on 2026-09-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0013_remove_legacy_stage_and_adequacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalresult",
            name="workflow_stage",
            field=models.CharField(
                choices=[
                    ("XRAY", "X-ray"),
                    ("CT", "CT"),
                    ("PET_CT_TNM", "PET-CT 및 TNM 병기 평가"),
                    ("PATHOLOGY_GENE", "조직·유전자 검사"),
                    ("PDL1", "PD-L1 검사"),
                    ("TREATMENT", "치료"),
                ],
                max_length=20,
            ),
        ),
    ]
