# Generated by Django 5.0.6 on 2026-09-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0015_prescriptionitem_mfds_item_seq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tnmresult",
            name="m_category",
            field=models.CharField(max_length=20),
        ),
    ]
