# Generated by Django 5.0.6 on 2026-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0016_alter_tnmresult_m_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentdecision",
            name="treatment_line",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1L", "First-line"),
                    ("2L", "Second-line"),
                    ("3L_PLUS", "Third-line or later"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
