# Generated by Django 5.0.6 on 2026-09-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0017_treatmentdecision_treatment_line"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treatmentdecision",
            name="treatment_line",
        ),
    ]
