# Generated by Django 5.0.6 on 2026-08-28 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_stage', models.CharField(choices=[('XRAY', 'X-ray'), ('CT', 'CT'), ('PATHOLOGY', '병리'), ('STAGING', '병기(TNM)'), ('GENE', '유전자'), ('TREATMENT', '치료'), ('PRESCRIPTION', '처방')], max_length=20)),
                ('image_type', models.CharField(choices=[('XRAY', 'X-ray'), ('CT', 'CT'), ('WSI', 'WSI')], max_length=10)),
                ('storage_type', models.CharField(choices=[('ORTHANC', 'Orthanc'), ('GCS', 'GCS')], max_length=10)),
                ('storage_uri', models.CharField(max_length=1000, unique=True)),
                ('file_format', models.CharField(max_length=20)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPLOADING', '업로드중'), ('VALIDATING', '검증중'), ('READY', '사용가능'), ('FAILED', '실패'), ('INVALID', '유효하지않음')], default='UPLOADING', max_length=15)),
            ],
            options={
                'db_table': 'case_image_assets',
            },
        ),
        migrations.CreateModel(
            name='ExaminationOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.CharField(choices=[('XRAY', 'X-ray'), ('CT', 'CT'), ('WSI', 'WSI')], max_length=10)),
                ('priority', models.CharField(choices=[('NORMAL', '일반'), ('URGENT', '긴급')], default='NORMAL', max_length=10)),
                ('purpose', models.TextField()),
                ('clinical_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ORDERED', '요청됨'), ('SCHEDULED', '예약됨'), ('COMPLETED', '완료'), ('CANCELLED', '취소됨')], default='ORDERED', max_length=15)),
            ],
            options={
                'db_table': 'examination_orders',
            },
        ),
        migrations.CreateModel(
            name='LungCancerCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_code', models.CharField(max_length=50, unique=True)),
                ('current_stage', models.CharField(choices=[('XRAY', 'X-ray'), ('CT', 'CT'), ('PATHOLOGY', '병리'), ('STAGING', '병기(TNM)'), ('GENE', '유전자'), ('TREATMENT', '치료'), ('PRESCRIPTION', '처방')], max_length=20)),
                ('case_status', models.CharField(choices=[('ACTIVE', '진행중'), ('REFERRED_OUT', '전원'), ('CLOSED', '종결')], default='ACTIVE', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lung_cancer_cases',
            },
        ),
        migrations.CreateModel(
            name='ClinicianDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_stage', models.CharField(choices=[('XRAY', 'X-ray'), ('CT', 'CT'), ('PATHOLOGY', '병리'), ('STAGING', '병기(TNM)'), ('GENE', '유전자'), ('TREATMENT', '치료'), ('PRESCRIPTION', '처방')], max_length=20)),
                ('decision_type', models.CharField(choices=[('PROCEED_NEXT_STAGE', '다음 단계 진행'), ('REPEAT_EXAMINATION', '재검사'), ('REFERRED_OUT', '전원'), ('CLOSE_CASE', '종결')], max_length=25)),
                ('target_stage', models.CharField(blank=True, choices=[('XRAY', 'X-ray'), ('CT', 'CT'), ('PATHOLOGY', '병리'), ('STAGING', '병기(TNM)'), ('GENE', '유전자'), ('TREATMENT', '치료'), ('PRESCRIPTION', '처방')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField()),
                ('decided_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinician_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinician_decisions',
            },
        ),
    ]
