# Generated by Django 5.0.6 on 2026-08-28 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('clinical', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniciandecision',
            name='source_clinical_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinician_decisions', to='clinical.clinicalresult'),
        ),
        migrations.AddField(
            model_name='examinationorder',
            name='requesting_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_examinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseimageasset',
            name='examination_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_assets', to='cases.examinationorder'),
        ),
        migrations.AddField(
            model_name='lungcancercase',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='lungcancercase',
            name='primary_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examinationorder',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examination_orders', to='cases.lungcancercase'),
        ),
        migrations.AddField(
            model_name='cliniciandecision',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinician_decisions', to='cases.lungcancercase'),
        ),
        migrations.AddField(
            model_name='caseimageasset',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_assets', to='cases.lungcancercase'),
        ),
        migrations.AddConstraint(
            model_name='lungcancercase',
            constraint=models.UniqueConstraint(condition=models.Q(('case_status', 'ACTIVE')), fields=('patient',), name='uq_case_one_active_per_patient'),
        ),
    ]
