# Generated by Django 5.0.6 on 2026-09-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examinationorder",
            name="pathology_test_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUBTYPE", "아형분류 검사"),
                    ("PDL1", "PD-L1 검사"),
                    ("GENE", "유전자 검사"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
