# Generated by Django 5.0.6 on 2026-09-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_remove_legacy_workflow_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseimageasset",
            name="workflow_stage",
            field=models.CharField(
                choices=[
                    ("XRAY", "X-ray"),
                    ("CT", "CT"),
                    ("PET_CT_TNM", "PET-CT 및 TNM 병기 평가"),
                    ("PATHOLOGY_GENE", "조직·유전자 검사"),
                    ("PDL1", "PD-L1 검사"),
                    ("TREATMENT", "치료"),
                    ("PRESCRIPTION", "처방"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cliniciandecision",
            name="source_stage",
            field=models.CharField(
                choices=[
                    ("XRAY", "X-ray"),
                    ("CT", "CT"),
                    ("PET_CT_TNM", "PET-CT 및 TNM 병기 평가"),
                    ("PATHOLOGY_GENE", "조직·유전자 검사"),
                    ("PDL1", "PD-L1 검사"),
                    ("TREATMENT", "치료"),
                    ("PRESCRIPTION", "처방"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cliniciandecision",
            name="target_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XRAY", "X-ray"),
                    ("CT", "CT"),
                    ("PET_CT_TNM", "PET-CT 및 TNM 병기 평가"),
                    ("PATHOLOGY_GENE", "조직·유전자 검사"),
                    ("PDL1", "PD-L1 검사"),
                    ("TREATMENT", "치료"),
                    ("PRESCRIPTION", "처방"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="examinationorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("XRAY", "X-ray"),
                    ("CT", "CT"),
                    ("PET_CT_TNM", "PET-CT 및 TNM 병기 평가"),
                    ("PATHOLOGY_GENE", "조직·유전자 검사"),
                    ("PDL1", "PD-L1 검사"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lungcancercase",
            name="current_stage",
            field=models.CharField(
                choices=[
                    ("XRAY", "X-ray"),
                    ("CT", "CT"),
                    ("PET_CT_TNM", "PET-CT 및 TNM 병기 평가"),
                    ("PATHOLOGY_GENE", "조직·유전자 검사"),
                    ("PDL1", "PD-L1 검사"),
                    ("TREATMENT", "치료"),
                    ("PRESCRIPTION", "처방"),
                ],
                max_length=20,
            ),
        ),
    ]
