# Generated by Django 5.0.6 on 2026-09-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_alter_caseimageasset_workflow_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseimageasset",
            name="orthanc_series_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="caseimageasset",
            name="series_instance_uid",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="caseimageasset",
            name="study_instance_uid",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="caseimageasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPLOADING", "업로드 중"),
                    ("VALIDATING", "검증 중"),
                    ("READY", "사용 가능"),
                    ("FAILED", "실패"),
                    ("INVALID", "유효하지 않음"),
                ],
                default="UPLOADING",
                max_length=15,
            ),
        ),
    ]
