# Generated by Django 5.0.6 on 2026-09-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0009_caseimageasset_orthanc_series_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseimageasset",
            name="orthanc_study_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
