# Generated by Django 5.0.6 on 2026-09-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_caseconsultationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseimageasset",
            name="orthanc_series_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="caseimageasset",
            name="series_instance_uid",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="caseimageasset",
            name="storage_uri",
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AddConstraint(
            model_name="caseimageasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("image_type", "CT"), _negated=True),
                fields=("storage_uri",),
                name="uq_caseimageasset_storage_uri_non_ct",
            ),
        ),
        migrations.AddConstraint(
            model_name="caseimageasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("image_type", "CT"), _negated=True),
                fields=("series_instance_uid",),
                name="uq_caseimageasset_series_uid_non_ct",
            ),
        ),
        migrations.AddConstraint(
            model_name="caseimageasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("image_type", "CT"), _negated=True),
                fields=("orthanc_series_id",),
                name="uq_caseimageasset_orthanc_series_non_ct",
            ),
        ),
    ]
