"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRespiratoryAuth } from "../_components/respiratory-auth-provider";

type Profile = { name: string; username: string; department?: { name?: string }; hospital?: { name?: string }; role?: string; doctor_profile?: { license_number?: string; birth_date?: string | null; gender?: string | null; profile_image_uri?: string | null; tags?: string[] } | null };
type NotificationType = "EXAMINATION_ORDER" | "CASE_CHAT";
type NotificationSetting = { notification_type: NotificationType; enabled: boolean };
const apiBase = (process.env.NEXT_PUBLIC_API_BASE_URL || "http://127.0.0.1:8000").replace(/\/+$/, "");

export default function RespiratorySettingsPage() {
  const { authorizedFetch } = useRespiratoryAuth();
  const [profile, setProfile] = useState<Profile | null>(null);
  const [licenseNumber, setLicenseNumber] = useState("");
  const [birthDate, setBirthDate] = useState("");
  const [gender, setGender] = useState("");
  const [imageUri, setImageUri] = useState("");
  const [tags, setTags] = useState("");
  const [message, setMessage] = useState("");
  const [orderNotificationsEnabled, setOrderNotificationsEnabled] = useState(true);
  const [caseChatNotificationsEnabled, setCaseChatNotificationsEnabled] = useState(true);
  const [notificationSaving, setNotificationSaving] = useState(false);

  useEffect(() => { void authorizedFetch(`${apiBase}/api/auth/staff/profile/`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.detail || "프로필을 불러오지 못했습니다."); const loaded = data as Profile; const doctor = loaded.doctor_profile; setProfile(loaded); setLicenseNumber(doctor?.license_number || ""); setBirthDate(doctor?.birth_date || ""); setGender(doctor?.gender || ""); setImageUri(doctor?.profile_image_uri || ""); setTags((doctor?.tags || []).join(", ")); }).catch((error) => setMessage(error instanceof Error ? error.message : "프로필을 불러오지 못했습니다.")); }, [authorizedFetch]);
  useEffect(() => { void Promise.all((["EXAMINATION_ORDER", "CASE_CHAT"] as NotificationType[]).map(async (notificationType) => { const response = await authorizedFetch(`${apiBase}/api/notifications/me/settings/?notification_type=${notificationType}`); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "알림 설정을 불러오지 못했습니다."); return data as NotificationSetting; })).then(([orderSetting, chatSetting]) => { setOrderNotificationsEnabled(orderSetting.enabled !== false); setCaseChatNotificationsEnabled(chatSetting.enabled !== false); }).catch((error) => setMessage(error instanceof Error ? error.message : "알림 설정을 불러오지 못했습니다.")); }, [authorizedFetch]);

  const save = async (event: FormEvent) => { event.preventDefault(); const response = await authorizedFetch(`${apiBase}/api/auth/staff/profile/`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ license_number: licenseNumber, birth_date: birthDate || null, gender: gender || null, profile_image_uri: imageUri || null, tags: tags.split(",").map((tag) => tag.trim()).filter(Boolean) }) }); const data = await response.json(); if (!response.ok) { setMessage(data.detail || "저장하지 못했습니다."); return; } setProfile(data); setMessage("프로필 설정을 저장했습니다."); };
  const saveNotificationSettings = async () => { setNotificationSaving(true); try { const settings: NotificationSetting[] = [{ notification_type: "EXAMINATION_ORDER", enabled: orderNotificationsEnabled }, { notification_type: "CASE_CHAT", enabled: caseChatNotificationsEnabled }]; const responses = await Promise.all(settings.map(async (setting) => { const response = await authorizedFetch(`${apiBase}/api/notifications/me/settings/`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(setting) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "알림 설정을 저장하지 못했습니다."); return data as NotificationSetting; })); setOrderNotificationsEnabled(responses[0].enabled); setCaseChatNotificationsEnabled(responses[1].enabled); setMessage("알림 설정을 저장했습니다."); } catch (error) { setMessage(error instanceof Error ? error.message : "알림 설정을 저장하지 못했습니다."); } finally { setNotificationSaving(false); } };

  return <div className="mx-auto h-full max-w-3xl overflow-y-auto p-6"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold text-blue-600">의사 설정</p><h1 className="mt-1 text-xl font-bold text-slate-900">내 프로필</h1><p className="mt-2 text-sm text-slate-500">진료과와 병원 소속 정보는 관리자 관리 영역입니다.</p>{!profile ? <p className="py-12 text-sm text-slate-400">프로필을 불러오는 중입니다.</p> : <><form onSubmit={save} className="mt-6 space-y-5"><div className="grid gap-4 sm:grid-cols-2"><ReadField label="이름" value={profile.name} /><ReadField label="로그인 ID" value={profile.username} /><ReadField label="병원" value={profile.hospital?.name || "-"} /><ReadField label="진료과 / 역할" value={`${profile.department?.name || "-"} / ${profile.role || "-"}`} /><TextField label="의사 면허번호" value={licenseNumber} onChange={setLicenseNumber} required /><label className="text-sm font-medium text-slate-700">생년월일<input type="date" value={birthDate} onChange={(event) => setBirthDate(event.target.value)} className="mt-1.5 block w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label><label className="text-sm font-medium text-slate-700">성별<select value={gender} onChange={(event) => setGender(event.target.value)} className="mt-1.5 block w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">미기입</option><option value="MALE">남성</option><option value="FEMALE">여성</option><option value="OTHER">기타</option></select></label><TextField label="프로필 이미지 URL" value={imageUri} onChange={setImageUri} placeholder="https://..." /></div><label className="block text-sm font-medium text-slate-700">전문 분야 태그<input value={tags} onChange={(event) => setTags(event.target.value)} placeholder="폐암, 흉부 CT, 기관지내시경" className="mt-1.5 block w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /><span className="mt-1 block text-xs text-slate-400">쉼표로 구분하여 최대 10개까지 저장할 수 있습니다.</span></label><button type="submit" className="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">저장</button></form><section className="mt-6 border-t border-slate-200 pt-5"><h2 className="text-base font-bold text-slate-900">알림 설정</h2><NotificationToggle title="검사 오더 알림" description="내 담당 Case에 새 검사 오더가 생성되면 알립니다." enabled={orderNotificationsEnabled} onChange={setOrderNotificationsEnabled} /><NotificationToggle title="개인 Case 메시지 알림" description="나를 수신자로 지정한 개인 Case 메시지가 도착하면 알립니다. 메시지 본문은 알림에 포함하지 않습니다." enabled={caseChatNotificationsEnabled} onChange={setCaseChatNotificationsEnabled} /><button type="button" disabled={notificationSaving} onClick={() => void saveNotificationSettings()} className="mt-3 rounded-lg border border-blue-200 bg-blue-50 px-4 py-2 text-sm font-semibold text-blue-700 disabled:bg-slate-100">{notificationSaving ? "저장 중..." : "알림 설정 저장"}</button></section>{message && <p className="mt-5 rounded-lg bg-blue-50 px-3 py-2 text-sm text-blue-700">{message}</p>}</>}</div></div>;
}

function ReadField({ label, value }: { label: string; value: string }) { return <label className="text-sm font-medium text-slate-700">{label}<input value={value} readOnly className="mt-1.5 block w-full rounded-lg border border-slate-100 bg-slate-50 px-3 py-2 text-sm text-slate-500" /></label>; }
function TextField({ label, value, onChange, required = false, placeholder }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; placeholder?: string }) { return <label className="text-sm font-medium text-slate-700">{label}<input required={required} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-1.5 block w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label>; }
function NotificationToggle({ title, description, enabled, onChange }: { title: string; description: string; enabled: boolean; onChange: (enabled: boolean) => void }) { return <div className="mt-3 flex items-center justify-between gap-4 rounded-lg bg-slate-50 p-4"><div><p className="text-sm font-semibold text-slate-800">{title}</p><p className="mt-1 text-xs text-slate-500">{description}</p></div><label className="flex shrink-0 items-center gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={(event) => onChange(event.target.checked)} /> 수신</label></div>; }
