"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRespiratoryAuth } from "../_components/respiratory-auth-provider";

type Profile = { name: string; username: string; department?: { name?: string }; hospital?: { name?: string }; role?: string; doctor_profile?: { license_number?: string; birth_date?: string | null; gender?: string | null; profile_image_uri?: string | null; tags?: string[] } | null };
const apiBase = (process.env.NEXT_PUBLIC_API_BASE_URL || "http://127.0.0.1:8000").replace(/\/+$/, "");

export default function RespiratorySettingsPage() {
  const { authorizedFetch } = useRespiratoryAuth();
  const [profile, setProfile] = useState<Profile | null>(null);
  const [licenseNumber, setLicenseNumber] = useState("");
  const [birthDate, setBirthDate] = useState("");
  const [gender, setGender] = useState("");
  const [imageUri, setImageUri] = useState("");
  const [tags, setTags] = useState("");
  const [message, setMessage] = useState("");

  useEffect(() => { void authorizedFetch(`${apiBase}/api/auth/staff/profile/`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.detail || "프로필을 불러오지 못했습니다."); setProfile(data); const doctor = data.doctor_profile; setLicenseNumber(doctor?.license_number || ""); setBirthDate(doctor?.birth_date || ""); setGender(doctor?.gender || ""); setImageUri(doctor?.profile_image_uri || ""); setTags((doctor?.tags || []).join(", ")); }).catch((error) => setMessage(error instanceof Error ? error.message : "프로필을 불러오지 못했습니다.")); }, [authorizedFetch]);
  const save = async (event: FormEvent) => { event.preventDefault(); const response = await authorizedFetch(`${apiBase}/api/auth/staff/profile/`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ license_number: licenseNumber, birth_date: birthDate || null, gender: gender || null, profile_image_uri: imageUri || null, tags: tags.split(",").map((tag) => tag.trim()).filter(Boolean) }) }); const data = await response.json(); if (!response.ok) { setMessage(data.detail || "저장하지 못했습니다."); return; } setProfile(data); setMessage("프로필 설정을 저장했습니다."); };
  return <div className="mx-auto h-full max-w-3xl overflow-y-auto p-6"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold text-blue-600">의사 설정</p><h1 className="mt-1 text-xl font-bold text-slate-900">내 프로필</h1><p className="mt-2 text-sm text-slate-500">진료과와 병원 소속 정보는 관리자 관리 항목입니다.</p>{!profile ? <p className="py-12 text-sm text-slate-400">프로필을 불러오는 중입니다.</p> : <form onSubmit={save} className="mt-6 space-y-5"><div className="grid gap-4 sm:grid-cols-2"><ReadField label="이름" value={profile.name} /><ReadField label="로그인 ID" value={profile.username} /><ReadField label="병원" value={profile.hospital?.name || "-"} /><ReadField label="진료과 / 역할" value={`${profile.department?.name || "-"} / ${profile.role || "-"}`} /><label className="text-sm font-medium text-slate-700">의사 면허번호<input required value={licenseNumber} onChange={(event) => setLicenseNumber(event.target.value)} className="mt-1.5 block w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label><label className="text-sm font-medium text-slate-700">생년월일<input type="date" value={birthDate} onChange={(event) => setBirthDate(event.target.value)} className="mt-1.5 block w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label><label className="text-sm font-medium text-slate-700">성별<select value={gender} onChange={(event) => setGender(event.target.value)} className="mt-1.5 block w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">미기재</option><option value="MALE">남성</option><option value="FEMALE">여성</option><option value="OTHER">기타</option></select></label><label className="text-sm font-medium text-slate-700">프로필 이미지 URL<input value={imageUri} onChange={(event) => setImageUri(event.target.value)} placeholder="https://..." className="mt-1.5 block w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label></div><label className="block text-sm font-medium text-slate-700">전문 분야 태그<input value={tags} onChange={(event) => setTags(event.target.value)} placeholder="폐암, 흉부 CT, 기관지내시경" className="mt-1.5 block w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /><span className="mt-1 block text-xs text-slate-400">쉼표로 구분하며 최대 10개까지 저장할 수 있습니다.</span></label>{message && <p className="rounded-lg bg-blue-50 px-3 py-2 text-sm text-blue-700">{message}</p>}<button type="submit" className="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">저장</button></form>}</div></div>;
}

function ReadField({ label, value }: { label: string; value: string }) { return <label className="text-sm font-medium text-slate-700">{label}<input value={value} readOnly className="mt-1.5 block w-full rounded-lg border border-slate-100 bg-slate-50 px-3 py-2 text-sm text-slate-500" /></label>; }
