# Generated by Django 5.0.6 on 2026-08-28 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'case_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotation_type', models.CharField(choices=[('POINT', '점'), ('BOUNDING_BOX', '박스'), ('POLYGON', '다각형'), ('FREEHAND', '자유곡선'), ('TEXT', '텍스트')], max_length=15)),
                ('annotation_data', models.JSONField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image_annotations',
            },
        ),
    ]
