# Generated by Django 5.0.6 on 2026-08-28 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotations', '0001_initial'),
        ('cases', '0001_initial'),
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casebookmark',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='cases.lungcancercase'),
        ),
        migrations.AddField(
            model_name='casebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='clinical_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='clinical.clinicalresult'),
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='image_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='cases.caseimageasset'),
        ),
        migrations.AddConstraint(
            model_name='casebookmark',
            constraint=models.UniqueConstraint(fields=('user', 'case'), name='uq_bookmark_user_case'),
        ),
    ]
