# Generated by Django 5.0.6 on 2026-08-28 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('channel', models.CharField(choices=[('IN_APP', '인앱'), ('PUSH', '푸시')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', '대기'), ('SENT', '발송완료'), ('FAILED', '실패')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to='cases.lungcancercase')),
                ('recipient_patient_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to='patients.patientaccount')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_logs',
            },
        ),
        migrations.CreateModel(
            name='PatientNotificationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('APPOINTMENT', '예약'), ('EXAMINATION', '검사일정'), ('RESULT', '검사결과'), ('MEDICATION', '복약'), ('QUESTIONNAIRE', '문진'), ('HEALTH', '건강관리')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='patients.patientaccount')),
            ],
            options={
                'db_table': 'patient_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('AI_ANALYSIS_COMPLETED', 'AI분석완료'), ('CLINICAL_REVIEW_REQUIRED', '검토필요'), ('APPOINTMENT', '예약'), ('CASE_STAGE_CHANGED', '단계변경'), ('SYSTEM', '시스템')], max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('recipient_patient_account__isnull', True), ('recipient_user__isnull', False)), models.Q(('recipient_patient_account__isnull', False), ('recipient_user__isnull', True)), _connector='OR'), name='ck_notiflog_exactly_one_recipient'),
        ),
        migrations.AddConstraint(
            model_name='patientnotificationsetting',
            constraint=models.UniqueConstraint(fields=('patient_account', 'notification_type'), name='uq_patient_notif_setting'),
        ),
        migrations.AddConstraint(
            model_name='usernotificationsetting',
            constraint=models.UniqueConstraint(fields=('user', 'notification_type'), name='uq_user_notif_setting'),
        ),
    ]
