# Generated by Django 5.0.6 on 2026-09-16 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("patients", "0008_currentmedication_mfds_item_seq_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=512, unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("ANDROID", "Android"), ("IOS", "iOS")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "patient_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to="patients.patientaccount",
                    ),
                ),
            ],
            options={
                "db_table": "patient_device_tokens",
                "indexes": [
                    models.Index(
                        fields=["patient_account", "is_active"],
                        name="idx_patient_device_active",
                    )
                ],
            },
        ),
    ]
