from django.urls import path

from .views import (
    CasePathologyAiAnalysisListAPIView,
    CasePathologyDiagnosisListAPIView,
    CasePathologySpecimenListAPIView,
    CasePathologyReportListAPIView,
    CasePDL1AiAnalysisListAPIView,
    CasePDL1AnalysisRunAPIView,
    CaseSpecimenAdequacyAiAnalysisListAPIView,
    PathologyWorkItemDetailAPIView,
    PathologyWorkItemListAPIView,
    PathologyWorkstationListAPIView,
    PathologySubmitForReviewAPIView,
    PathologyDiagnosisConfirmAPIView,
    PathologyDiagnosisDetailAPIView,
    SpecimenWholeSlideImageListAPIView,
    WholeSlideImagePyramidAPIView,
    WholeSlideImageTileAPIView,
)

app_name = "pathology"

urlpatterns = [
    path(
        "cases/<uuid:case_id>/submit-for-review/",
        PathologySubmitForReviewAPIView.as_view(),
        name="case-submit-for-review",
    ),
    path(
        "workstation/",
        PathologyWorkstationListAPIView.as_view(),
        name="workstation-list",
    ),
    path(
        "work-items/",
        PathologyWorkItemListAPIView.as_view(),
        name="work-item-list",
    ),
    path(
        "work-items/<uuid:id>/",
        PathologyWorkItemDetailAPIView.as_view(),
        name="work-item-detail",
    ),
    path(
        "cases/<uuid:case_id>/specimens/",
        CasePathologySpecimenListAPIView.as_view(),
        name="case-specimen-list",
    ),
    path(
        "cases/<uuid:case_id>/ai-results/",
        CasePathologyAiAnalysisListAPIView.as_view(),
        name="case-ai-result-list",
    ),
    path(
        "cases/<uuid:case_id>/adequacy-results/",
        CaseSpecimenAdequacyAiAnalysisListAPIView.as_view(),
        name="case-adequacy-result-list",
    ),
    path(
        "cases/<uuid:case_id>/pdl1-results/",
        CasePDL1AiAnalysisListAPIView.as_view(),
        name="case-pdl1-result-list",
    ),
    path(
        "cases/<uuid:case_id>/pdl1-results/run/",
        CasePDL1AnalysisRunAPIView.as_view(),
        name="case-pdl1-analysis-run",
    ),
    path(
        "cases/<uuid:case_id>/diagnoses/",
        CasePathologyDiagnosisListAPIView.as_view(),
        name="case-diagnosis-list",
    ),
    path(
        "cases/<uuid:case_id>/reports/",
        CasePathologyReportListAPIView.as_view(),
        name="case-report-list",
    ),
    path(
        "diagnoses/<uuid:diagnosis_id>/",
        PathologyDiagnosisDetailAPIView.as_view(),
        name="diagnosis-detail",
    ),
    path(
        "diagnoses/<uuid:diagnosis_id>/confirm/",
        PathologyDiagnosisConfirmAPIView.as_view(),
        name="diagnosis-confirm",
    ),
    path(
        "specimens/<uuid:specimen_id>/wsis/",
        SpecimenWholeSlideImageListAPIView.as_view(),
        name="specimen-wsi-list",
    ),
    path(
        "wsis/<uuid:wsi_id>/pyramid/",
        WholeSlideImagePyramidAPIView.as_view(),
        name="wsi-pyramid",
    ),
    path(
        "wsis/<uuid:wsi_id>/tiles/<int:level>/<int:x>/<int:y>/",
        WholeSlideImageTileAPIView.as_view(),
        name="wsi-tile",
    ),
]
