from django.urls import path

from .views import (
    CasePathologyAiAnalysisListAPIView,
    CasePathologyGeneAnalysisCancelAPIView,
    CasePathologyGeneAnalysisRunAPIView,
    CasePathologyDiagnosisListAPIView,
    CasePathologySpecimenListAPIView,
    CasePathologyReportListAPIView,
    CasePDL1AiAnalysisListAPIView,
    CasePDL1AnalysisRunAPIView,
    PDL1TestSampleListAPIView,
    PathologyOrderPDL1InputUploadAPIView,
    PathologyOrderPathologyGeneInputUploadAPIView,
    PathologyWorkItemDetailAPIView,
    PathologyWorkItemListAPIView,
    PathologyCaseWorkflowAPIView,
    PathologyWorkstationListAPIView,
    PathologySubmitForReviewAPIView,
    PathologyDiagnosisConfirmAPIView,
    PathologyDiagnosisDetailAPIView,
    SpecimenWholeSlideImageListAPIView,
    WholeSlideImagePyramidAPIView,
    WholeSlideImageTileAPIView,
)

app_name = "pathology"

urlpatterns = [
    path(
        "cases/<uuid:case_id>/submit-for-review/",
        PathologySubmitForReviewAPIView.as_view(),
        name="case-submit-for-review",
    ),
    path(
        "workstation/",
        PathologyWorkstationListAPIView.as_view(),
        name="workstation-list",
    ),
    path(
        "cases/<uuid:case_id>/workflow/",
        PathologyCaseWorkflowAPIView.as_view(),
        name="case-workflow",
    ),
    path(
        "work-items/",
        PathologyWorkItemListAPIView.as_view(),
        name="work-item-list",
    ),
    path(
        "work-items/<uuid:id>/",
        PathologyWorkItemDetailAPIView.as_view(),
        name="work-item-detail",
    ),
    path(
        "cases/<uuid:case_id>/specimens/",
        CasePathologySpecimenListAPIView.as_view(),
        name="case-specimen-list",
    ),
    path(
        "cases/<uuid:case_id>/ai-results/",
        CasePathologyAiAnalysisListAPIView.as_view(),
        name="case-ai-result-list",
    ),
    path(
        "cases/<uuid:case_id>/ai-results/run/",
        CasePathologyGeneAnalysisRunAPIView.as_view(),
        name="case-pathology-gene-analysis-run",
    ),
    path(
        "cases/<uuid:case_id>/ai-results/<uuid:analysis_id>/cancel/",
        CasePathologyGeneAnalysisCancelAPIView.as_view(),
        name="case-pathology-gene-analysis-cancel",
    ),
    path(
        "cases/<uuid:case_id>/pdl1-results/",
        CasePDL1AiAnalysisListAPIView.as_view(),
        name="case-pdl1-result-list",
    ),
    path(
        "cases/<uuid:case_id>/pdl1-results/run/",
        CasePDL1AnalysisRunAPIView.as_view(),
        name="case-pdl1-analysis-run",
    ),
    path(
        "pdl1-test-samples/",
        PDL1TestSampleListAPIView.as_view(),
        name="pdl1-test-sample-list",
    ),
    path(
        "orders/<uuid:order_id>/pdl1-input/",
        PathologyOrderPDL1InputUploadAPIView.as_view(),
        name="order-pdl1-input-upload",
    ),
    path(
        "orders/<uuid:order_id>/pathology-gene-input/",
        PathologyOrderPathologyGeneInputUploadAPIView.as_view(),
        name="order-pathology-gene-input-upload",
    ),
    path(
        "cases/<uuid:case_id>/diagnoses/",
        CasePathologyDiagnosisListAPIView.as_view(),
        name="case-diagnosis-list",
    ),
    path(
        "cases/<uuid:case_id>/reports/",
        CasePathologyReportListAPIView.as_view(),
        name="case-report-list",
    ),
    path(
        "diagnoses/<uuid:diagnosis_id>/",
        PathologyDiagnosisDetailAPIView.as_view(),
        name="diagnosis-detail",
    ),
    path(
        "diagnoses/<uuid:diagnosis_id>/confirm/",
        PathologyDiagnosisConfirmAPIView.as_view(),
        name="diagnosis-confirm",
    ),
    path(
        "specimens/<uuid:specimen_id>/wsis/",
        SpecimenWholeSlideImageListAPIView.as_view(),
        name="specimen-wsi-list",
    ),
    path(
        "wsis/<uuid:wsi_id>/pyramid/",
        WholeSlideImagePyramidAPIView.as_view(),
        name="wsi-pyramid",
    ),
    path(
        "wsis/<uuid:wsi_id>/tiles/<int:level>/<int:x>/<int:y>/",
        WholeSlideImageTileAPIView.as_view(),
        name="wsi-tile",
    ),
]
