"use client";

import { FormEvent, useCallback, useEffect, useRef, useState } from "react";

type AuthorizedFetch = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
type Message = { id: string; body: string; sender: { id: string; name: string; department: string; role: string }; created_at: string };
const API = process.env.NEXT_PUBLIC_API_BASE_URL || "http://127.0.0.1:8000";
const WS = (process.env.NEXT_PUBLIC_REALTIME_WS_URL?.trim() || "ws://127.0.0.1:8001").replace(/\/+$/, "");

export function SoomChatPanel({ authorizedFetch }: { authorizedFetch: AuthorizedFetch }) {
  const [open, setOpen] = useState(false), [messages, setMessages] = useState<Message[]>([]), [body, setBody] = useState("");
  const [unread, setUnread] = useState(0), [next, setNext] = useState<string | null>(null), [status, setStatus] = useState("offline"), [error, setError] = useState("");
  const socket = useRef<WebSocket | null>(null), timeline = useRef<HTMLDivElement | null>(null), reconnect = useRef<number | null>(null), disposed = useRef(false);
  const merge = useCallback((incoming: Message[]) => setMessages(current => Array.from(new Map([...current, ...incoming].map(m => [m.id, m])).values()).sort((a,b) => new Date(a.created_at).getTime()-new Date(b.created_at).getTime())), []);
  const refreshUnread = useCallback(async () => { const r = await authorizedFetch(`${API}/api/chat/global/messages/unread-count/`); const p = await r.json().catch(() => ({})); if (r.ok) setUnread(p.unread_count || 0); }, [authorizedFetch]);
  const load = useCallback(async (cursor?: string | null) => { const r = await authorizedFetch(`${API}/api/chat/global/messages/${cursor ? `?cursor=${encodeURIComponent(cursor)}` : ""}`); const p = await r.json(); if (!r.ok) throw new Error(p.detail || "숨챗을 불러오지 못했습니다."); merge(p.results || []); setNext(typeof p.next_cursor === "string" ? p.next_cursor : null); if (p.results?.length) { await authorizedFetch(`${API}/api/chat/global/messages/read/`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message_ids: p.results.map((m: Message) => m.id) }) }); await refreshUnread(); } }, [authorizedFetch, merge, refreshUnread]);
  useEffect(() => { if (!open) return; void Promise.resolve().then(() => load()).catch(e => setError(e.message)); }, [load, open]);
  useEffect(() => { void Promise.resolve().then(() => refreshUnread()).catch(() => undefined); const t = window.setInterval(() => void refreshUnread().catch(() => undefined), 30000); return () => window.clearInterval(t); }, [refreshUnread]);
  useEffect(() => { if (!open) return; disposed.current = false; const connect = () => { const token = window.sessionStorage.getItem("accessToken"); if (!token || disposed.current) return; setStatus("connecting"); const s = new WebSocket(`${WS}/ws/chat/global`, ["soomit-chat", token]); socket.current = s; s.onopen = () => { setStatus("connected"); setError(""); }; s.onmessage = e => { try { const p = JSON.parse(e.data); if (p.type === "chat.message.created" && p.message) { merge([p.message]); s.send(JSON.stringify({ type: "chat.message.read", message_id: p.message.id })); void refreshUnread(); } if (p.type === "chat.error") setError(p.detail || "메시지를 처리하지 못했습니다."); } catch { setError("채팅 이벤트를 해석하지 못했습니다."); } }; s.onclose = () => { if (!disposed.current) { setStatus("offline"); reconnect.current = window.setTimeout(connect, 1500); } }; }; connect(); return () => { disposed.current = true; if (reconnect.current) window.clearTimeout(reconnect.current); socket.current?.close(); socket.current = null; setStatus("offline"); }; }, [merge, open, refreshUnread]);
  useEffect(() => { if (open && timeline.current) timeline.current.scrollTop = timeline.current.scrollHeight; }, [messages, open]);
  function send(e: FormEvent) { e.preventDefault(); const value = body.trim(); if (!value || !socket.current || socket.current.readyState !== WebSocket.OPEN) return; socket.current.send(JSON.stringify({ type: "chat.message.create", client_message_id: crypto.randomUUID(), body: value })); setBody(""); }
  return <div className="fixed bottom-5 right-5 z-50" data-chat-no-drag="true">{open ? <section className="flex h-[min(620px,calc(100vh-40px))] w-[min(380px,calc(100vw-32px))] flex-col overflow-hidden rounded-2xl border border-blue-100 bg-white shadow-2xl" aria-label="숨챗"><header className="flex items-center justify-between bg-gradient-to-r from-blue-700 to-blue-500 px-4 py-3 text-white"><div><p className="text-sm font-bold">숨챗</p><p className="text-[11px] text-blue-100">의료진 공용방 · {status === "connected" ? "실시간 연결됨" : status === "connecting" ? "연결 중" : "연결 대기"}</p></div><button type="button" onClick={() => setOpen(false)} className="px-2 text-xl">×</button></header><div ref={timeline} className="min-h-0 flex-1 space-y-3 overflow-y-auto bg-slate-50 p-3"><p className="rounded-lg bg-blue-50 px-3 py-2 text-[11px] text-blue-800">같은 병원의 의사·방사선사·병리사가 함께 참여하는 공용 채팅입니다.</p>{next && <button type="button" onClick={() => void load(next)} className="mx-auto block text-xs underline">이전 메시지 불러오기</button>}{messages.map(m => <article key={m.id} className="rounded-xl border bg-white p-3"><div className="flex justify-between"><span className="text-xs font-semibold text-blue-800">{m.sender.name}</span><span className="text-[10px] text-slate-400">{new Date(m.created_at).toLocaleTimeString("ko-KR", { hour: "2-digit", minute: "2-digit" })}</span></div><p className="mt-1 whitespace-pre-wrap break-words text-sm text-slate-700">{m.body}</p></article>)}</div><form onSubmit={send} className="border-t bg-white p-3">{error && <p className="mb-2 text-xs text-rose-600">{error}</p>}<div className="flex gap-2"><textarea value={body} onChange={e => setBody(e.target.value)} className="min-h-10 min-w-0 flex-1 resize-none rounded-lg border p-2 text-xs" placeholder="메시지를 입력하세요." maxLength={2000}/><button type="submit" disabled={!body.trim() || status !== "connected"} className="self-end rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white disabled:bg-slate-300">전송</button></div></form></section> : <button type="button" onClick={() => setOpen(true)} className="relative rounded-full bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-lg hover:bg-blue-700">숨챗{unread > 0 && <span className="absolute -right-1 -top-1 min-w-5 rounded-full bg-rose-500 px-1.5 text-center text-[10px] leading-5">{unread > 99 ? "99+" : unread}</span>}</button>}</div>;
}
