# Generated by Django 5.0.6 on 2026-09-13 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_results", "0004_aianalysis_examination_order"),
        ("cases", "0003_examinationorder_pathology_test_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RadiologyReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "의사 판독 대기"),
                            ("IN_PROGRESS", "의사 판독 진행 중"),
                            ("COMPLETED", "의사 판독 완료"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "ai_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="radiology_reviews",
                        to="ai_results.aianalysis",
                    ),
                ),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_radiology_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="radiology_reviews",
                        to="cases.lungcancercase",
                    ),
                ),
                (
                    "examination_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="radiology_reviews",
                        to="cases.examinationorder",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_radiology_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "radiology_reviews",
                "indexes": [
                    models.Index(
                        fields=["assigned_doctor", "status"],
                        name="idx_radreview_doctor_status",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="radiologyreview",
            constraint=models.UniqueConstraint(
                fields=("examination_order", "ai_analysis"),
                name="uq_radiology_review_order_analysis",
            ),
        ),
    ]
