steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, --file, Dockerfile.core, --tag, gcr.io/$PROJECT_ID/tnm-serve:$_IMAGE_TAG, .]
images: [gcr.io/$PROJECT_ID/tnm-serve:$_IMAGE_TAG]
substitutions: {_IMAGE_TAG: latest}
timeout: 1800s
