steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, --file, Dockerfile.m, --tag, gcr.io/$PROJECT_ID/tnm-m-serve:$_IMAGE_TAG, .]
images: [gcr.io/$PROJECT_ID/tnm-m-serve:$_IMAGE_TAG]
substitutions: {_IMAGE_TAG: latest}
timeout: 3600s
options:
  machineType: E2_HIGHCPU_32
