steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, --file, Dockerfile.t, --tag, gcr.io/$PROJECT_ID/tnm-t-serve:latest, .]
images: [gcr.io/$PROJECT_ID/tnm-t-serve:latest]
timeout: 3600s
options:
  machineType: E2_HIGHCPU_32
