"use client";

import { useEffect, useState, type FormEvent } from "react";
import { useSearchParams } from "next/navigation";
import Alert from "@/components/common/Alert";
import Input from "@/components/common/Input";
import { StateMessage } from "@/components/workspace/state-message";
import { createHospitalAdmin, fetchHospitalAdmins, fetchHospitals, SystemAdminApiError, type Hospital, type HospitalAdmin } from "../_lib/system-admin-api";
import { getSystemAdminAccessToken } from "../_lib/system-admin-session";
import { SystemAdminActionButton } from "./system-admin-action-button";

const apiMessage = (caught: unknown) => caught instanceof SystemAdminApiError && caught.status === 401 ? "인증이 만료되었습니다. 다시 로그인해주세요." : caught instanceof SystemAdminApiError && caught.status === 403 ? "시스템 관리자 권한이 없습니다." : caught instanceof Error ? caught.message : "요청을 처리하지 못했습니다.";

export function HospitalAdminManagement() {
  const params = useSearchParams();
  const [hospitals, setHospitals] = useState<Hospital[]>([]); const [admins, setAdmins] = useState<HospitalAdmin[]>([]);
  const [filter, setFilter] = useState(""); const [form, setForm] = useState({ hospital_id: "", login_id: "", name: "", password: "" });
  const [state, setState] = useState<"loading" | "ready" | "empty" | "error">("loading"); const [saving, setSaving] = useState(false);
  const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const [reloadKey, setReloadKey] = useState(0);
  const requestedHospitalId = params.get("hospital_id") || "";

  useEffect(() => { const controller = new AbortController(); async function load() { await Promise.resolve(); const token = getSystemAdminAccessToken(); if (!token) return; try { const rows = await fetchHospitals(token, controller.signal); const initialHospitalId = rows.some((row) => row.id === requestedHospitalId) ? requestedHospitalId : ""; setHospitals(rows); setFilter(""); setForm((current) => ({ ...current, hospital_id: initialHospitalId || rows[0]?.id || "" })); } catch (caught) { if (controller.signal.aborted || (caught instanceof Error && caught.name === "AbortError")) return; setError(apiMessage(caught)); setState("error"); } } void load(); return () => controller.abort(); }, [requestedHospitalId]);
  useEffect(() => { const controller = new AbortController(); async function load() { await Promise.resolve(); const token = getSystemAdminAccessToken(); if (!token) return; setState("loading"); try { const rows = await fetchHospitalAdmins(token, filter || undefined, controller.signal); setAdmins(rows); setState(rows.length ? "ready" : "empty"); } catch (caught) { if (controller.signal.aborted || (caught instanceof Error && caught.name === "AbortError")) return; setError(apiMessage(caught)); setState("error"); } } void load(); return () => controller.abort(); }, [filter, reloadKey]);
  async function submit(event: FormEvent) { event.preventDefault(); const token = getSystemAdminAccessToken(); if (!token) return; setSaving(true); setError(""); setSuccess(""); try { await createHospitalAdmin(token, form); setForm((current) => ({ ...current, login_id: "", name: "", password: "" })); setSuccess("HospitalAdmin 계정을 생성했습니다."); setFilter(""); setReloadKey((current) => current + 1); } catch (caught) { setError(apiMessage(caught)); } finally { setSaving(false); } }
  const normalizedFilter = filter;

  return <div className="grid gap-7 xl:grid-cols-[minmax(0,1.3fr)_minmax(340px,0.7fr)]"><section className="border-y border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-200 p-4"><h2 className="font-bold">HospitalAdmin 목록</h2><select value={normalizedFilter} onChange={(event) => setFilter(event.target.value)} className="rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">전체 병원</option>{hospitals.map((hospital) => <option key={hospital.id} value={hospital.id}>{hospital.name}</option>)}</select></div>{state === "loading" ? <StateMessage variant="loading" title="관리자 목록을 불러오는 중입니다." className="m-5" /> : null}{state === "empty" ? <StateMessage variant="empty" title="등록된 병원 관리자가 없습니다." className="m-5" /> : null}{state === "error" ? <StateMessage variant="error" title="관리자 목록을 조회할 수 없습니다." description={error} className="m-5" /> : null}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3">아이디</th><th className="p-3">이름</th><th className="p-3">상태</th><th className="p-3">병원</th></tr></thead><tbody className="divide-y divide-slate-100">{admins.map((admin) => <tr key={admin.id}><td className="p-3 font-medium">{admin.login_id}</td><td className="p-3">{admin.name}</td><td className="p-3">{admin.account_status}</td><td className="p-3">{admin.hospital.name} · {admin.hospital.code}</td></tr>)}</tbody></table></div></section>
    <form onSubmit={submit} className="h-fit border-y border-slate-200 bg-white p-5"><h2 className="font-bold">HospitalAdmin 생성</h2><div className="mt-5 space-y-4"><label className="block text-sm font-semibold text-slate-700">병원<select required value={form.hospital_id} onChange={(event) => setForm((current) => ({ ...current, hospital_id: event.target.value }))} className="mt-2 h-12 w-full rounded-lg border border-slate-300 px-3"><option value="">병원 선택</option>{hospitals.map((hospital) => <option key={hospital.id} value={hospital.id}>{hospital.name} · {hospital.code}</option>)}</select></label><Input required label="아이디" placeholder="아이디를 입력하세요" value={form.login_id} onChange={(event) => setForm((current) => ({ ...current, login_id: event.target.value }))} /><Input required label="이름" value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} /><Input required label="비밀번호" type="password" value={form.password} onChange={(event) => setForm((current) => ({ ...current, password: event.target.value }))} autoComplete="new-password" /></div><div className="mt-4"><Alert message={error} />{success ? <p role="status" className="border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{success}</p> : null}</div><div className="mt-5 flex justify-end"><SystemAdminActionButton type="submit" disabled={saving || hospitals.length === 0}>{saving ? "생성 중..." : "관리자 생성"}</SystemAdminActionButton></div></form></div>;
}
