"use client";

import { useEffect, useState } from "react";
import { StateMessage } from "@/components/workspace/state-message";
import { fetchHospitalDetail, fetchHospitals, SystemAdminApiError, type Hospital, type HospitalDetail } from "../_lib/system-admin-api";
import { getSystemAdminAccessToken } from "../_lib/system-admin-session";

const message = (caught: unknown) => caught instanceof SystemAdminApiError && caught.status === 401 ? "인증이 만료되었습니다. 다시 로그인해주세요." : caught instanceof SystemAdminApiError && caught.status === 403 ? "시스템 관리자 권한이 없습니다." : caught instanceof Error ? caught.message : "조회하지 못했습니다.";

export function HospitalManagement() {
  const [items, setItems] = useState<Hospital[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [detail, setDetail] = useState<HospitalDetail | null>(null);
  const [listState, setListState] = useState<"loading" | "ready" | "empty" | "error">("loading");
  const [detailState, setDetailState] = useState<"idle" | "loading" | "ready" | "error">("idle");
  const [error, setError] = useState("");

  useEffect(() => { const controller = new AbortController(); async function load() { await Promise.resolve(); const token = getSystemAdminAccessToken(); if (!token) return; try { const rows = await fetchHospitals(token, controller.signal); setItems(rows); setSelectedId((current) => current && rows.some((row) => row.id === current) ? current : rows[0]?.id ?? null); setListState(rows.length ? "ready" : "empty"); } catch (caught) { if (controller.signal.aborted || (caught instanceof Error && caught.name === "AbortError")) return; setError(message(caught)); setListState("error"); } } void load(); return () => controller.abort(); }, []);
  useEffect(() => { if (!selectedId) return; const controller = new AbortController(); async function load() { await Promise.resolve(); const token = getSystemAdminAccessToken(); if (!token) return; setDetailState("loading"); try { setDetail(await fetchHospitalDetail(token, selectedId!, controller.signal)); setDetailState("ready"); } catch (caught) { if (controller.signal.aborted || (caught instanceof Error && caught.name === "AbortError")) return; setError(message(caught)); setDetailState("error"); } } void load(); return () => controller.abort(); }, [selectedId]);

  return <div className="grid min-h-[650px] border-y border-slate-200 bg-white lg:grid-cols-[minmax(320px,0.85fr)_minmax(0,1.4fr)] lg:divide-x lg:divide-slate-200"><section><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-bold">병원 목록</h2></div>{listState === "loading" ? <StateMessage variant="loading" title="병원 목록을 불러오는 중입니다." className="m-5" /> : null}{listState === "empty" ? <StateMessage variant="empty" title="등록된 병원이 없습니다." className="m-5" /> : null}{listState === "error" ? <StateMessage variant="error" title="병원 목록을 조회할 수 없습니다." description={error} className="m-5" /> : null}<div className="divide-y divide-slate-100">{items.map((item) => <button type="button" key={item.id} onClick={() => setSelectedId(item.id)} className={`grid w-full grid-cols-[1fr_auto] gap-2 px-5 py-4 text-left hover:bg-blue-50 ${selectedId === item.id ? "bg-blue-50" : ""}`}><span className="font-semibold">{item.name}</span><span className="text-xs text-slate-500">{item.code}</span><span className="col-span-2 text-xs text-slate-500">{item.phone || "전화번호 없음"}</span></button>)}</div></section>
    <section className="min-w-0 bg-slate-50 p-5">{detailState === "idle" ? <StateMessage variant="empty" title="병원을 선택해주세요." /> : null}{detailState === "loading" ? <StateMessage variant="loading" title="병원 상세를 불러오는 중입니다." /> : null}{detailState === "error" ? <StateMessage variant="error" title="병원 상세를 조회할 수 없습니다." description={error} /> : null}{detailState === "ready" && detail ? <><div className="border-b border-slate-200 pb-5"><h2 className="text-xl font-bold">{detail.name}</h2><p className="mt-1 text-sm text-slate-500">{detail.code} · {detail.phone || "전화번호 없음"}</p><p className="mt-2 text-sm text-slate-600">{detail.address || "주소 없음"}</p></div><section className="py-5"><h3 className="font-bold">부서 및 역할</h3><div className="mt-3 divide-y divide-slate-200 border-y border-slate-200 bg-white">{detail.departments.map((department) => <div key={department.id} className="px-4 py-3"><div className="flex justify-between"><span className="font-semibold">{department.name}</span><span className="text-xs text-slate-500">{department.code}</span></div><p className="mt-2 text-sm text-slate-600">{department.roles.map((role) => role.display_name).join(", ") || "등록된 역할 없음"}</p></div>)}</div></section><section className="border-t border-slate-200 pt-5"><h3 className="font-bold">HospitalAdmin</h3><div className="mt-3 space-y-2">{detail.hospital_admins.map((admin) => <div key={admin.id} className="flex justify-between border-b border-slate-200 pb-2 text-sm"><span>{admin.name} · {admin.login_id}</span><span className="text-slate-500">{admin.account_status}</span></div>)}{detail.hospital_admins.length === 0 ? <p className="text-sm text-slate-500">등록된 병원 관리자가 없습니다.</p> : null}</div></section></> : null}</section></div>;
}
