# Generated by Django 5.0.6 on 2026-08-28 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('VIEW', '조회'), ('CREATE', '생성'), ('UPDATE', '수정'), ('DELETE', '삭제'), ('CONFIRM', '확정'), ('CANCEL', '취소'), ('STATUS_CHANGE', '상태변경'), ('LOGIN', '로그인'), ('LOGOUT', '로그아웃')], max_length=15)),
                ('target_table', models.CharField(max_length=100)),
                ('target_id', models.UUIDField()),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
    ]
