General:
  MODEL_NAME: AMD_MIL
  seed: 42
  num_classes: 3
  num_epochs: 10
  device: 0
  num_workers: 4
  best_model_metric: macro_auc
  earlystop:
    use: false
    patience: 5
    metric: macro_auc
Dataset:
  DATASET_NAME: PDL1_TPS_Virchow2
  dataset_csv_path: null
  dataset_root_dir: /home/jupyter-mirae9/pdl1_amd_3fold_clean
  balanced_sampler:
    use: false
    replacement: true
Logs:
  log_root_dir: /home/jupyter-mirae9/pdl1_amd_logs
Model:
  in_dim: 2560
  dropout: 0.25
  embed_dim: 512
  agent_num: 256
  act: relu
  optimizer:
    which: adam
    adam_config:
      lr: 0.0002
      weight_decay: 1.0e-05
    adamw_config:
      lr: 0.0002
      weight_decay: 1.0e-05
  criterion: ce
  scheduler:
    warmup: 0
    which: step
    step_config:
      step_size: 3
      gamma: 0.9
    multi_step_config:
      milestones:
      - 20
      - 30
      - 40
      gamma: 0.9
    exponential_config:
      gamma: 0.9
    cosine_config:
      T_max: 10
      eta_min: 0.0001
