# Generated by Django 5.0.6 on 2026-08-28 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0001_initial'),
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('MALE', '남'), ('FEMALE', '여'), ('OTHER', '기타'), ('UNKNOWN', '미상')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number_hash', models.CharField(db_index=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='accounts.hospital')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_time', models.TimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_schedules', to='clinical.prescription')),
            ],
            options={
                'db_table': 'medication_schedules',
            },
        ),
        migrations.CreateModel(
            name='MedicationIntakeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('TAKEN', '복용완료'), ('MISSED', '미복용'), ('SKIPPED', '건너뜀')], default='PENDING', max_length=10)),
                ('medication_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_logs', to='patients.medicationschedule')),
            ],
            options={
                'db_table': 'medication_intake_logs',
            },
        ),
        migrations.CreateModel(
            name='MedicationScheduleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='patients.medicationschedule')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_items', to='clinical.prescriptionitem')),
            ],
            options={
                'db_table': 'medication_schedule_items',
            },
        ),
        migrations.CreateModel(
            name='PatientHealthProfile',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health_profile', serialize=False, to='patients.patient')),
                ('smoking_status', models.CharField(blank=True, choices=[('NEVER', '비흡연'), ('FORMER', '과거흡연'), ('CURRENT', '현재흡연'), ('UNKNOWN', '미상')], max_length=10, null=True)),
                ('smoking_start_age', models.SmallIntegerField(blank=True, null=True)),
                ('smoking_end_age', models.SmallIntegerField(blank=True, null=True)),
                ('cigarettes_per_day', models.SmallIntegerField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('comorbidities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patient_health_profiles',
            },
        ),
        migrations.CreateModel(
            name='PatientAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number_hash', models.CharField(max_length=64, unique=True)),
                ('phone_verified_at', models.DateTimeField()),
                ('link_status', models.CharField(choices=[('UNLINKED', '미연결'), ('PENDING_REVIEW', '확인대기'), ('LINKED', '연결됨'), ('REJECTED', '거부됨')], default='UNLINKED', max_length=20)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('linked_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_patient_accounts', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_accounts',
            },
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='patient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_schedules', to='patients.patientaccount'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('appointment_status', models.CharField(choices=[('REQUESTED', '요청됨'), ('CONFIRMED', '확정됨'), ('CANCELLED', '취소됨')], max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('visit_status', models.CharField(choices=[('SCHEDULED', '예정'), ('VISITED', '방문완료'), ('NO_SHOW', '미방문')], max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_type', models.CharField(choices=[('PATIENT', '환자'), ('DOCTOR_ORDER', '의사오더'), ('SYSTEM', '시스템')], max_length=20)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='cases.lungcancercase')),
                ('confirmed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('examination_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='cases.examinationorder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('cancellation_requested_by_patient_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancel_requested_appointments', to='patients.patientaccount')),
                ('created_by_patient_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_appointments', to='patients.patientaccount')),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='PatientQuestionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire_type', models.CharField(max_length=50)),
                ('questionnaire_version', models.CharField(max_length=30)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaires', to='cases.lungcancercase')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionnaires', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_questionnaires',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('GOOGLE', 'Google'), ('KAKAO', 'Kakao'), ('NAVER', 'Naver')], max_length=10)),
                ('provider_uid', models.CharField(max_length=255)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('patient_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='patients.patientaccount')),
            ],
            options={
                'db_table': 'social_accounts',
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptom_type', models.CharField(max_length=50)),
                ('symptom_description', models.TextField(blank=True, null=True)),
                ('severity', models.SmallIntegerField()),
                ('risk_level', models.CharField(choices=[('GREEN', '정상'), ('YELLOW', '주의'), ('RED', '위험')], max_length=10)),
                ('logged_at', models.DateTimeField()),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='symptom_logs', to='cases.lungcancercase')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptom_logs', to='patients.patient')),
            ],
            options={
                'db_table': 'symptom_logs',
            },
        ),
        migrations.AddConstraint(
            model_name='medicationintakelog',
            constraint=models.UniqueConstraint(fields=('medication_schedule', 'scheduled_at'), name='uq_medintake_schedule_time'),
        ),
        migrations.AddConstraint(
            model_name='medicationscheduleitem',
            constraint=models.UniqueConstraint(fields=('medication_schedule', 'prescription_item'), name='uq_medschedule_item'),
        ),
        migrations.AddConstraint(
            model_name='patienthealthprofile',
            constraint=models.CheckConstraint(check=models.Q(('smoking_start_age__gte', 0)), name='ck_php_smoke_start_ge0'),
        ),
        migrations.AddConstraint(
            model_name='patienthealthprofile',
            constraint=models.CheckConstraint(check=models.Q(('smoking_end_age__gte', models.F('smoking_start_age')), ('smoking_end_age__isnull', True), _connector='OR'), name='ck_php_smoke_end_ge_start'),
        ),
        migrations.AddConstraint(
            model_name='patienthealthprofile',
            constraint=models.CheckConstraint(check=models.Q(('cigarettes_per_day__gte', 0)), name='ck_php_cigs_ge0'),
        ),
        migrations.AddConstraint(
            model_name='patienthealthprofile',
            constraint=models.CheckConstraint(check=models.Q(('height_cm__gt', 0)), name='ck_php_height_gt0'),
        ),
        migrations.AddConstraint(
            model_name='patienthealthprofile',
            constraint=models.CheckConstraint(check=models.Q(('weight_kg__gt', 0)), name='ck_php_weight_gt0'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['hospital', 'phone_number_hash'], name='idx_patient_hosp_phonehash'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name', 'birth_date'], name='idx_patient_name_birth'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('hospital', 'patient_code'), name='uq_patient_hospital_code'),
        ),
        migrations.AddConstraint(
            model_name='patientaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('patient__isnull', False)), fields=('patient',), name='uq_patient_account_patient'),
        ),
        migrations.AddConstraint(
            model_name='medicationschedule',
            constraint=models.UniqueConstraint(fields=('patient_account', 'prescription', 'reminder_time'), name='uq_medschedule'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_uid'), name='uq_social_provider_uid'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('patient_account', 'provider'), name='uq_social_account_provider'),
        ),
        migrations.AddConstraint(
            model_name='symptomlog',
            constraint=models.CheckConstraint(check=models.Q(('severity__gte', 0), ('severity__lte', 10)), name='ck_symptom_severity_0_10'),
        ),
    ]
