# Generated by Django 5.0.6 on 2026-08-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_by_type',
            field=models.CharField(choices=[('PATIENT', '환자'), ('DOCTOR_ORDER', '의사오더')], max_length=20),
        ),
    ]
