# Generated by Django 5.0.6 on 2026-09-06 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
        ("patients", "0002_alter_appointment_created_by_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentMedication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("medication_name", models.CharField(max_length=200)),
                (
                    "ingredient_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "dose",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("dose_unit", models.CharField(blank=True, max_length=30, null=True)),
                ("frequency", models.CharField(blank=True, max_length=100, null=True)),
                ("route", models.CharField(blank=True, max_length=30, null=True)),
                ("started_at", models.DateField(blank=True, null=True)),
                ("ended_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "drug",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_current_medications",
                        to="clinical.drug",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_medications",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_current_medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "current_medications",
                "indexes": [
                    models.Index(
                        fields=["patient", "is_active"],
                        name="idx_curmed_patient_active",
                    )
                ],
            },
        ),
    ]
