# Generated by Django 5.0.6 on 2026-09-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_labresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="address_detail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
