# Generated by Django 5.0.6 on 2026-09-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_patient_address_detail_patient_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientaccount",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patientaccount",
            name="address_detail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patientaccount",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientaccount",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patientaccount",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="patientaccount",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MALE", "남"),
                    ("FEMALE", "여"),
                    ("OTHER", "기타"),
                    ("UNKNOWN", "미상"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patientaccount",
            name="phone_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
