# Generated by Django 5.0.6 on 2026-09-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_add_patient_account_profile_fields"),
        ("patients", "0006_appointmentrequest_and_more"),
    ]

    operations = []
