# Generated by Django 5.0.6 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("patients", "0008_currentmedication_mfds_item_seq_and_more")]

    operations = [
        migrations.AddField(
            model_name="medicationschedule",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicationschedule",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicationschedule",
            name="repeat_type",
            field=models.CharField(choices=[("DAILY", "Daily"), ("WEEKLY", "Specific weekdays"), ("CYCLE_DAY", "Treatment cycle days")], default="DAILY", max_length=15),
        ),
        migrations.AddField(
            model_name="medicationschedule",
            name="repeat_weekdays",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="medicationschedule",
            name="cycle_days",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
