# Generated by Django 5.0.6 on 2026-09-18 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0009_medication_schedule_recurrence"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientQrToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_tokens",
                        to="patients.patientaccount",
                    ),
                ),
            ],
            options={
                "db_table": "patient_qr_tokens",
                "indexes": [
                    models.Index(
                        fields=["patient_account", "expires_at"],
                        name="idx_patient_qr_expiry",
                    )
                ],
            },
        ),
    ]
