"use client";
import { useState } from "react";
import { apiJson } from "./preview-api";
import type { AuthorizedFetch } from "../../cases/[caseId]/treatment-prescription-types";
import type { Prescription, Safety } from "./preview-types";
export function PreviewSafetyPanel({caseId,base,fetcher,prescription,onRefresh}:{caseId:string;base:string;fetcher:AuthorizedFetch;prescription?:Prescription;onRefresh:()=>void}){
 const [status,setStatus]=useState("UNCONFIRMED"),[allergies,setAllergies]=useState(""),[medications,setMedications]=useState(""),[labs,setLabs]=useState({creatinine:"",egfr:"",ast:"",alt:"",total_bilirubin:""}),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const blocked=["DUR_API_ERROR","DUR_MAPPING_UNRESOLVED","ALLERGY_UNCONFIRMED","LAB_MISSING"];
 const run=async()=>{if(!prescription)return;setBusy(true);setError("");try{await apiJson(fetcher,base,`/api/doctor/cases/${caseId}/prescriptions/${prescription.id}/preview-safety/`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({allergy_status:status,allergies:allergies.split(",").map(v=>v.trim()).filter(Boolean),current_medications:medications.split("\n").filter(Boolean).map(line=>{const [medication_name,ingredient_name,mfds_item_seq=""]=line.split("|").map(v=>v.trim());return {medication_name,ingredient_name,mfds_item_seq};}),...labs})});onRefresh()}catch(e){setError(e instanceof Error?e.message:"Safety Check 실패")}finally{setBusy(false)}};
 const results:Safety[]=prescription?.safety_check_results??[], unresolved=results.some(r=>r.result==="BLOCK"||blocked.includes(r.source_code??"")), needsAck=results.some(r=>r.result==="WARNING"&&!r.acknowledged_at&&!blocked.includes(r.source_code??"")), canFinalize=Boolean(prescription&&prescription.items.length&&prescription.items.every(i=>i.final_dose!=null)&&results.length&&!unresolved&&!needsAck);
 const acknowledge=async()=>{if(!prescription)return;const note=window.prompt("WARNING 확인 사유를 입력하세요.","Preview 검토 완료");if(!note?.trim())return;setBusy(true);try{await apiJson(fetcher,base,`/api/doctor/cases/${caseId}/prescriptions/${prescription.id}/preview-warnings/acknowledge/`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({acknowledgment_note:note.trim()})});onRefresh()}catch(e){setError(e instanceof Error?e.message:"WARNING 확인 실패")}finally{setBusy(false)}};
 const finalize=async()=>{if(!prescription)return;setBusy(true);try{await apiJson(fetcher,base,`/api/doctor/cases/${caseId}/prescriptions/${prescription.id}/preview-finalize/`,{method:"POST"});onRefresh()}catch(e){setError(e instanceof Error?e.message:"처방 확정 실패")}finally{setBusy(false)}};
 return <section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="text-base font-bold">Safety Check</h2>{prescription&&<div className="mt-3 space-y-3"><div><p className="text-xs font-semibold">알레르기</p><div className="mt-1 flex gap-3 text-sm">{[["NONE","없음"],["PRESENT","있음"],["UNCONFIRMED","확인되지 않음"]].map(([v,l])=><label key={v}><input type="radio" checked={status===v} onChange={()=>setStatus(v)}/> {l}</label>)}</div>{status==="PRESENT"&&<input value={allergies} onChange={e=>setAllergies(e.target.value)} placeholder="알레르기 약물/성분 (쉼표 구분)" className="mt-2 w-full rounded border p-2 text-sm"/>}</div><label className="block text-xs font-semibold">현재 복용약<textarea value={medications} onChange={e=>setMedications(e.target.value)} placeholder="약물명|성분명|MFDS ITEM_SEQ (한 줄에 하나)" rows={3} className="mt-1 w-full rounded border p-2 text-sm font-normal"/></label><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{Object.keys(labs).map(key=><label key={key} className="text-xs font-semibold">{key}<input type="number" value={labs[key as keyof typeof labs]} onChange={e=>setLabs(current=>({...current,[key]:e.target.value}))} className="mt-1 w-full rounded border p-2 font-normal"/></label>)}</div><div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={()=>void run()} className="rounded bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?"검사 중...":"처방 안전성 검사"}</button>{needsAck&&<button type="button" disabled={busy} onClick={()=>void acknowledge()} className="rounded bg-amber-600 px-4 py-2 text-sm font-semibold text-white">WARNING 확인</button>}<button type="button" disabled={busy||!canFinalize} onClick={()=>void finalize()} className="rounded bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:bg-slate-300">처방 확정</button></div>{!canFinalize&&<p className="text-xs text-amber-700">{!prescription.items.every(i=>i.final_dose!=null)?"최종 처방량을 모두 입력하세요.":!results.length?"안전성 검사가 필요합니다.":unresolved?"해결되지 않은 경고가 있습니다.":needsAck?"일반 WARNING을 확인해 주세요.":"안전성 검사를 확인하세요."}</p>}{error&&<p role="alert" className="text-sm text-rose-600">{error}</p>}{results.map((r,i)=><div key={`${r.id}-${i}`} className="rounded border p-3 text-sm"><b>{r.result}</b><p className="mt-1 text-xs">{r.message}</p><p className="text-[11px] text-slate-400">{r.source_code??"-"}</p></div>)}</div>}</section>;
}
