# Generated by Django 5.0.6 on 2026-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="address_detail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
