# Generated by Django 5.0.6 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_hospital_address_detail_hospital_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("DOCTOR", "의사"),
                    ("TECHNOLOGIST", "방사선/임상병리사"),
                    ("MEDICAL_STAFF", "의료행정직"),
                ],
                max_length=20,
            ),
        ),
    ]
