#!/usr/bin/env python3

"""
visualization.py

Operational visualization for CPMNetv2 HN25.

Input
-----
- Original CT
    NIfTI file
    or DICOM series directory

- final_detections.json
    generated by Step 22

Output
------
visualization/
├── axial/
├── coronal/
├── sagittal/
├── preview_3d/
└── viewer_annotations.json

Purpose
-------
- Doctor-facing qualitative visualization
- CT slice overlay
- Bounding box visualization
- Viewer integration metadata

IMPORTANT
---------
This is operational visualization.

No GT is used.

Coordinates used:
- original_voxel
- physical_world XYZ mm
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import matplotlib.pyplot as plt
import numpy as np
import SimpleITK as sitk
from matplotlib.patches import Rectangle
from mpl_toolkits.mplot3d.art3d import Line3DCollection


# =============================================================================
# CONFIG
# =============================================================================

WINDOW_CENTER = -600.0
WINDOW_WIDTH = 1500.0

WINDOW_MIN = (
    WINDOW_CENTER
    - WINDOW_WIDTH / 2.0
)

WINDOW_MAX = (
    WINDOW_CENTER
    + WINDOW_WIDTH / 2.0
)

MAX_VISUALIZED_NODULES = 20


# =============================================================================
# IO
# =============================================================================

def load_json(
    path: Path | str,
) -> Dict[str, Any]:

    path = Path(
        path
    )

    if not path.exists():

        raise FileNotFoundError(
            f"JSON 없음:\n{path}"
        )

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as file:

        return json.load(
            file
        )


def load_nifti(
    path: Path,
) -> sitk.Image:

    return sitk.ReadImage(
        str(
            path
        ),
        sitk.sitkFloat32,
    )


def load_dicom_series(
    directory: Path,
    series_uid: Optional[str] = None,
) -> sitk.Image:

    series_ids = (
        sitk.ImageSeriesReader
        .GetGDCMSeriesIDs(
            str(
                directory
            )
        )
    )

    if not series_ids:

        raise RuntimeError(
            f"DICOM series 없음:\n{directory}"
        )

    series_ids = list(
        series_ids
    )

    if series_uid is None:

        if len(
            series_ids
        ) != 1:

            raise RuntimeError(
                "DICOM series가 여러 개 있습니다.\n"
                f"Available: {series_ids}"
            )

        selected_uid = (
            series_ids[0]
        )

    else:

        selected_uid = str(
            series_uid
        )

        if selected_uid not in series_ids:

            raise RuntimeError(
                "series_uid가 없습니다.\n"
                f"Requested: {selected_uid}\n"
                f"Available: {series_ids}"
            )

    filenames = (
        sitk.ImageSeriesReader
        .GetGDCMSeriesFileNames(
            str(
                directory
            ),
            selected_uid,
        )
    )

    reader = (
        sitk.ImageSeriesReader()
    )

    reader.SetFileNames(
        filenames
    )

    return sitk.Cast(
        reader.Execute(),
        sitk.sitkFloat32,
    )


def load_ct(
    input_path: Path | str,
    series_uid: Optional[str] = None,
) -> Tuple[
    sitk.Image,
    np.ndarray,
]:

    path = Path(
        input_path
    )

    if not path.exists():

        raise FileNotFoundError(
            f"CT 없음:\n{path}"
        )

    if path.is_dir():

        image = (
            load_dicom_series(
                directory=path,
                series_uid=series_uid,
            )
        )

    else:

        lower_name = (
            path.name.lower()
        )

        if (
            lower_name.endswith(
                ".nii"
            )
            or
            lower_name.endswith(
                ".nii.gz"
            )
        ):

            image = (
                load_nifti(
                    path
                )
            )

        else:

            raise RuntimeError(
                "지원하지 않는 CT 입력입니다."
            )

    volume = (
        sitk.GetArrayFromImage(
            image
        )
        .astype(
            np.float32
        )
    )

    return (
        image,
        volume,
    )


# =============================================================================
# DISPLAY
# =============================================================================

def window_ct(
    image: np.ndarray,
) -> np.ndarray:

    return np.clip(
        image,
        WINDOW_MIN,
        WINDOW_MAX,
    )


def clamp_index(
    value: float,
    size: int,
) -> int:

    return int(
        max(
            0,
            min(
                round(
                    value
                ),
                size - 1,
            ),
        )
    )


# =============================================================================
# BBOX HELPERS
# =============================================================================

def get_original_bbox(
    nodule: Dict[str, Any],
) -> Tuple[
    np.ndarray,
    np.ndarray,
]:

    original = (
        nodule[
            "original_voxel"
        ]
    )

    bbox_min = np.asarray(
        original[
            "bbox_min_zyx"
        ],
        dtype=np.float64,
    )

    bbox_max = np.asarray(
        original[
            "bbox_max_zyx"
        ],
        dtype=np.float64,
    )

    return (
        bbox_min,
        bbox_max,
    )


def get_original_center(
    nodule: Dict[str, Any],
) -> np.ndarray:

    return np.asarray(
        nodule[
            "original_voxel"
        ][
            "center_zyx"
        ],
        dtype=np.float64,
    )


# =============================================================================
# DRAW 2D
# =============================================================================

def draw_axial(
    volume: np.ndarray,
    nodule: Dict[str, Any],
    output_path: Path,
):

    center = (
        get_original_center(
            nodule
        )
    )

    bbox_min, bbox_max = (
        get_original_bbox(
            nodule
        )
    )

    z = clamp_index(
        center[0],
        volume.shape[0],
    )

    image = (
        volume[
            z
        ]
    )

    x_min = float(
        bbox_min[2]
    )

    y_min = float(
        bbox_min[1]
    )

    x_max = float(
        bbox_max[2]
    )

    y_max = float(
        bbox_max[1]
    )

    fig, ax = plt.subplots(
        figsize=(
            8,
            8,
        )
    )

    ax.imshow(
        window_ct(
            image
        ),
        cmap="gray",
        vmin=WINDOW_MIN,
        vmax=WINDOW_MAX,
    )

    rect = Rectangle(
        (
            x_min,
            y_min,
        ),
        x_max - x_min,
        y_max - y_min,
        fill=False,
        linewidth=2.2,
    )

    ax.add_patch(
        rect
    )

    ax.scatter(
        [
            center[2]
        ],
        [
            center[1]
        ],
        marker="x",
        s=90,
        linewidths=2,
    )

    ax.set_title(
        (
            f"{nodule['nodule_id']} | "
            f"Axial Z={z}\n"
            f"Score={nodule['score']:.4f}"
        )
    )

    ax.axis(
        "off"
    )

    fig.tight_layout()

    fig.savefig(
        output_path,
        dpi=180,
        bbox_inches="tight",
    )

    plt.close(
        fig
    )


def draw_coronal(
    volume: np.ndarray,
    nodule: Dict[str, Any],
    output_path: Path,
):

    center = (
        get_original_center(
            nodule
        )
    )

    bbox_min, bbox_max = (
        get_original_bbox(
            nodule
        )
    )

    y = clamp_index(
        center[1],
        volume.shape[1],
    )

    image = (
        volume[
            :,
            y,
            :
        ]
    )

    x_min = float(
        bbox_min[2]
    )

    z_min = float(
        bbox_min[0]
    )

    x_max = float(
        bbox_max[2]
    )

    z_max = float(
        bbox_max[0]
    )

    fig, ax = plt.subplots(
        figsize=(
            8,
            8,
        )
    )

    ax.imshow(
        window_ct(
            image
        ),
        cmap="gray",
        vmin=WINDOW_MIN,
        vmax=WINDOW_MAX,
        origin="lower",
    )

    rect = Rectangle(
        (
            x_min,
            z_min,
        ),
        x_max - x_min,
        z_max - z_min,
        fill=False,
        linewidth=2.2,
    )

    ax.add_patch(
        rect
    )

    ax.scatter(
        [
            center[2]
        ],
        [
            center[0]
        ],
        marker="x",
        s=90,
        linewidths=2,
    )

    ax.set_title(
        (
            f"{nodule['nodule_id']} | "
            f"Coronal Y={y}\n"
            f"Score={nodule['score']:.4f}"
        )
    )

    ax.axis(
        "off"
    )

    fig.tight_layout()

    fig.savefig(
        output_path,
        dpi=180,
        bbox_inches="tight",
    )

    plt.close(
        fig
    )


def draw_sagittal(
    volume: np.ndarray,
    nodule: Dict[str, Any],
    output_path: Path,
):

    center = (
        get_original_center(
            nodule
        )
    )

    bbox_min, bbox_max = (
        get_original_bbox(
            nodule
        )
    )

    x = clamp_index(
        center[2],
        volume.shape[2],
    )

    image = (
        volume[
            :,
            :,
            x
        ]
    )

    y_min = float(
        bbox_min[1]
    )

    z_min = float(
        bbox_min[0]
    )

    y_max = float(
        bbox_max[1]
    )

    z_max = float(
        bbox_max[0]
    )

    fig, ax = plt.subplots(
        figsize=(
            8,
            8,
        )
    )

    ax.imshow(
        window_ct(
            image
        ),
        cmap="gray",
        vmin=WINDOW_MIN,
        vmax=WINDOW_MAX,
        origin="lower",
    )

    rect = Rectangle(
        (
            y_min,
            z_min,
        ),
        y_max - y_min,
        z_max - z_min,
        fill=False,
        linewidth=2.2,
    )

    ax.add_patch(
        rect
    )

    ax.scatter(
        [
            center[1]
        ],
        [
            center[0]
        ],
        marker="x",
        s=90,
        linewidths=2,
    )

    ax.set_title(
        (
            f"{nodule['nodule_id']} | "
            f"Sagittal X={x}\n"
            f"Score={nodule['score']:.4f}"
        )
    )

    ax.axis(
        "off"
    )

    fig.tight_layout()

    fig.savefig(
        output_path,
        dpi=180,
        bbox_inches="tight",
    )

    plt.close(
        fig
    )


# =============================================================================
# 3D BBOX PREVIEW
# =============================================================================

def bbox_edges(
    corners: np.ndarray,
) -> List[
    Tuple[
        np.ndarray,
        np.ndarray,
    ]
]:

    pairs = [
        (0, 1),
        (0, 2),
        (0, 4),

        (1, 3),
        (1, 5),

        (2, 3),
        (2, 6),

        (3, 7),

        (4, 5),
        (4, 6),

        (5, 7),

        (6, 7),
    ]

    return [
        (
            corners[a],
            corners[b],
        )

        for a, b in pairs
    ]


def draw_3d_bbox(
    nodule: Dict[str, Any],
    output_path: Path,
):

    corners_xyz = np.asarray(
        nodule[
            "physical_world"
        ][
            "bbox_corners_xyz_mm"
        ],
        dtype=np.float64,
    )

    center_xyz = np.asarray(
        nodule[
            "physical_world"
        ][
            "center_xyz_mm"
        ],
        dtype=np.float64,
    )

    edges = (
        bbox_edges(
            corners_xyz
        )
    )

    segments = [
        [
            edge[0],
            edge[1],
        ]

        for edge in edges
    ]

    fig = plt.figure(
        figsize=(
            8,
            8,
        )
    )

    ax = fig.add_subplot(
        111,
        projection="3d",
    )

    collection = (
        Line3DCollection(
            segments,
            linewidths=2,
        )
    )

    ax.add_collection3d(
        collection
    )

    ax.scatter(
        [
            center_xyz[0]
        ],
        [
            center_xyz[1]
        ],
        [
            center_xyz[2]
        ],
        marker="o",
        s=60,
    )

    mins = (
        corners_xyz.min(
            axis=0
        )
    )

    maxs = (
        corners_xyz.max(
            axis=0
        )
    )

    padding = max(
        float(
            np.max(
                maxs - mins
            )
        )
        * 0.25,
        2.0,
    )

    ax.set_xlim(
        mins[0] - padding,
        maxs[0] + padding,
    )

    ax.set_ylim(
        mins[1] - padding,
        maxs[1] + padding,
    )

    ax.set_zlim(
        mins[2] - padding,
        maxs[2] + padding,
    )

    ax.set_xlabel(
        "World X (mm)"
    )

    ax.set_ylabel(
        "World Y (mm)"
    )

    ax.set_zlabel(
        "World Z (mm)"
    )

    ax.set_title(
        (
            f"{nodule['nodule_id']} 3D Bounding Box\n"
            f"Score={nodule['score']:.4f}"
        )
    )

    fig.tight_layout()

    fig.savefig(
        output_path,
        dpi=180,
        bbox_inches="tight",
    )

    plt.close(
        fig
    )


# =============================================================================
# VIEWER ANNOTATION
# =============================================================================

def build_viewer_annotation(
    nodule: Dict[str, Any],
) -> Dict[str, Any]:

    physical = (
        nodule[
            "physical_world"
        ]
    )

    original = (
        nodule[
            "original_voxel"
        ]
    )

    return {
        "annotation_id":
            nodule[
                "nodule_id"
            ],

        "type":
            "3D_BOUNDING_BOX",

        "score":
            float(
                nodule[
                    "score"
                ]
            ),

        "world_coordinate_system":
            "XYZ_mm",

        "center_world_xyz_mm":
            physical[
                "center_xyz_mm"
            ],

        "bbox_world": {
            "min_xyz_mm":
                physical[
                    "bbox_min_xyz_mm"
                ],

            "max_xyz_mm":
                physical[
                    "bbox_max_xyz_mm"
                ],

            "corners_xyz_mm":
                physical[
                    "bbox_corners_xyz_mm"
                ],
        },

        "original_voxel": {
            "center_zyx":
                original[
                    "center_zyx"
                ],

            "bbox_min_zyx":
                original[
                    "bbox_min_zyx"
                ],

            "bbox_max_zyx":
                original[
                    "bbox_max_zyx"
                ],
        },

        "slice_range_z":
            nodule[
                "viewer_helper"
            ][
                "original_slice_range_z"
            ],

        "display": {
            "label":
                (
                    f"{nodule['nodule_id']} "
                    f"{nodule['score']:.3f}"
                ),

            "show_score":
                True,

            "show_center":
                True,

            "show_bbox":
                True,
        },
    }


# =============================================================================
# COMPLETE VISUALIZATION
# =============================================================================

def generate_visualizations(
    input_ct: Path | str,
    detection_json: Path | str,
    output_dir: Path | str,
    series_uid: Optional[str] = None,
    max_nodules: int = MAX_VISUALIZED_NODULES,
):

    output_dir = Path(
        output_dir
    )

    axial_dir = (
        output_dir
        / "axial"
    )

    coronal_dir = (
        output_dir
        / "coronal"
    )

    sagittal_dir = (
        output_dir
        / "sagittal"
    )

    preview_3d_dir = (
        output_dir
        / "preview_3d"
    )

    for directory in [
        axial_dir,
        coronal_dir,
        sagittal_dir,
        preview_3d_dir,
    ]:

        directory.mkdir(
            parents=True,
            exist_ok=True,
        )

    # -------------------------------------------------------------------------
    # Load
    # -------------------------------------------------------------------------

    _, volume = (
        load_ct(
            input_path=input_ct,
            series_uid=series_uid,
        )
    )

    detection_data = (
        load_json(
            detection_json
        )
    )

    nodules = (
        detection_data.get(
            "nodules",
            []
        )
    )

    # score descending
    nodules = sorted(
        nodules,
        key=lambda item: float(
            item[
                "score"
            ]
        ),
        reverse=True,
    )

    # 여기서는 PNG 폭발 방지를 위해 상위 N개만 생성.
    #
    # Viewer annotation JSON은 전체 candidate를 저장한다.
    selected = nodules[
        :
        max_nodules
    ]

    print(
        "CT shape ZYX:",
        list(
            volume.shape
        ),
    )

    print(
        "Total detections:",
        len(
            nodules
        ),
    )

    print(
        "PNG visualized:",
        len(
            selected
        ),
    )

    # -------------------------------------------------------------------------
    # PNG
    # -------------------------------------------------------------------------

    manifest = []

    for index, nodule in enumerate(
        selected,
        start=1,
    ):

        nodule_id = (
            nodule[
                "nodule_id"
            ]
        )

        base_name = (
            f"{index:03d}_"
            f"{nodule_id}"
        )

        axial_path = (
            axial_dir
            / f"{base_name}.png"
        )

        coronal_path = (
            coronal_dir
            / f"{base_name}.png"
        )

        sagittal_path = (
            sagittal_dir
            / f"{base_name}.png"
        )

        preview_path = (
            preview_3d_dir
            / f"{base_name}.png"
        )

        draw_axial(
            volume=volume,
            nodule=nodule,
            output_path=axial_path,
        )

        draw_coronal(
            volume=volume,
            nodule=nodule,
            output_path=coronal_path,
        )

        draw_sagittal(
            volume=volume,
            nodule=nodule,
            output_path=sagittal_path,
        )

        draw_3d_bbox(
            nodule=nodule,
            output_path=preview_path,
        )

        manifest.append(
            {
                "nodule_id":
                    nodule_id,

                "rank":
                    index,

                "score":
                    float(
                        nodule[
                            "score"
                        ]
                    ),

                "axial_png":
                    str(
                        axial_path
                    ),

                "coronal_png":
                    str(
                        coronal_path
                    ),

                "sagittal_png":
                    str(
                        sagittal_path
                    ),

                "preview_3d_png":
                    str(
                        preview_path
                    ),
            }
        )

        print(
            f"[{index}/{len(selected)}] "
            f"{nodule_id} "
            f"score={nodule['score']:.4f}"
        )

    # -------------------------------------------------------------------------
    # Viewer annotations - ALL detections
    # -------------------------------------------------------------------------

    annotations = [
        build_viewer_annotation(
            nodule
        )

        for nodule in nodules
    ]

    viewer_payload = {
        "status":
            "SUCCESS",

        "case_id":
            detection_data.get(
                "case_id"
            ),

        "series_uid":
            detection_data.get(
                "series_uid"
            ),

        "annotation_coordinate_system":
            "patient physical XYZ mm",

        "annotation_count":
            len(
                annotations
            ),

        "annotations":
            annotations,
    }

    viewer_path = (
        output_dir
        / "viewer_annotations.json"
    )

    with open(
        viewer_path,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            viewer_payload,
            file,
            indent=2,
            ensure_ascii=False,
        )

    # -------------------------------------------------------------------------
    # Visualization manifest
    # -------------------------------------------------------------------------

    manifest_path = (
        output_dir
        / "visualization_manifest.json"
    )

    with open(
        manifest_path,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            manifest,
            file,
            indent=2,
            ensure_ascii=False,
        )

    return {
        "viewer_annotations":
            viewer_path,

        "visualization_manifest":
            manifest_path,

        "axial_dir":
            axial_dir,

        "coronal_dir":
            coronal_dir,

        "sagittal_dir":
            sagittal_dir,

        "preview_3d_dir":
            preview_3d_dir,
    }


# =============================================================================
# CLI
# =============================================================================

def main():

    parser = argparse.ArgumentParser(
        description=(
            "CPMNetv2 operational detection visualization"
        )
    )

    parser.add_argument(
        "--input",
        required=True,
        type=str,
        help=(
            "Original CT NIfTI or DICOM directory"
        ),
    )

    parser.add_argument(
        "--detections",
        required=True,
        type=str,
        help=(
            "Step 22 final_detections.json"
        ),
    )

    parser.add_argument(
        "--output-dir",
        required=True,
        type=str,
    )

    parser.add_argument(
        "--series-uid",
        default=None,
        type=str,
    )

    parser.add_argument(
        "--max-nodules",
        default=MAX_VISUALIZED_NODULES,
        type=int,
    )

    args = parser.parse_args()

    if args.max_nodules <= 0:

        raise ValueError(
            "--max-nodules는 1 이상이어야 합니다."
        )

    print(
        "=" * 100
    )

    print(
        "23 - CPMNetv2 Operational Visualization"
    )

    print(
        "=" * 100
    )

    print(
        "Input CT:"
    )

    print(
        args.input
    )

    print()

    print(
        "Detections:"
    )

    print(
        args.detections
    )

    print()

    print(
        "Output:"
    )

    print(
        args.output_dir
    )

    print()

    paths = (
        generate_visualizations(
            input_ct=args.input,
            detection_json=args.detections,
            output_dir=args.output_dir,
            series_uid=args.series_uid,
            max_nodules=args.max_nodules,
        )
    )

    print()

    print(
        "=" * 100
    )

    print(
        "Visualization Finished"
    )

    print(
        "=" * 100
    )

    for name, path in (
        paths.items()
    ):

        print(
            f"{name}:"
        )

        print(
            path
        )

    print()

    print(
        "[PASS] Step 23 operational visualization completed"
    )


if __name__ == "__main__":

    main()

