# Generated by Django 5.0.6 on 2026-09-16 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0010_caseimageasset_orthanc_study_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("client_message_id", models.UUIDField()),
                ("body", models.CharField(max_length=2000)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="cases.lungcancercase",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "case_chat_messages",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["case", "-created_at", "-id"],
                        name="idx_chat_case_cursor",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="casechatmessage",
            constraint=models.UniqueConstraint(
                fields=("case", "sender", "client_message_id"),
                name="uq_chat_case_sender_client_msg",
            ),
        ),
    ]
