# Generated by Django 5.0.6 on 2026-09-02 03:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PathologySpecimen",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("specimen_code", models.CharField(max_length=50)),
                (
                    "specimen_type",
                    models.CharField(
                        choices=[
                            ("BIOPSY", "생검"),
                            ("RESECTION", "절제 검체"),
                            ("CYTOLOGY", "세포 검체"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("body_site", models.CharField(blank=True, max_length=100, null=True)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "등록"),
                            ("RECEIVED", "접수"),
                            ("PROCESSING", "처리 중"),
                            ("READY", "분석 가능"),
                            ("INVALIDATED", "무효"),
                        ],
                        default="REGISTERED",
                        max_length=20,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pathology_specimens",
                        to="cases.lungcancercase",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pathology_specimens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "examination_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pathology_specimens",
                        to="cases.examinationorder",
                    ),
                ),
            ],
            options={
                "db_table": "pathology_specimens",
            },
        ),
        migrations.CreateModel(
            name="WholeSlideImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slide_code", models.CharField(max_length=50)),
                ("block_code", models.CharField(blank=True, max_length=50, null=True)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "stain",
                    models.CharField(
                        choices=[("HE", "H&E"), ("PDL1", "PD-L1"), ("OTHER", "기타")],
                        default="HE",
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64)),
                (
                    "mpp",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("invalidation_reason", models.TextField(blank=True, null=True)),
                (
                    "image_asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="whole_slide_image",
                        to="cases.caseimageasset",
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wsis",
                        to="pathology.pathologyspecimen",
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_whole_slide_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "whole_slide_images",
            },
        ),
        migrations.CreateModel(
            name="PathologyWorkItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("WSI_UPLOAD", "WSI 등록"),
                            ("QUALITY_CHECK", "WSI 품질검증"),
                            ("ADEQUACY_ANALYSIS", "적정성 AI 분석"),
                            ("ADEQUACY_REVIEW", "적정성 전문의 판정"),
                            ("PATHOLOGY_ANALYSIS", "병리 AI 분석"),
                            ("DIAGNOSTIC_REVIEW", "병리 전문의 판독"),
                            ("REPORT_REVIEW", "병리 보고서 검토"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("IN_PROGRESS", "진행 중"),
                            ("BLOCKED", "차단"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("NORMAL", "일반"),
                            ("REVIEW_REQUIRED", "검토 필요"),
                            ("CRITICAL", "중요"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_pathology_work_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pathology_work_items",
                        to="cases.lungcancercase",
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_items",
                        to="pathology.pathologyspecimen",
                    ),
                ),
                (
                    "wsi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_items",
                        to="pathology.wholeslideimage",
                    ),
                ),
            ],
            options={
                "db_table": "pathology_work_items",
            },
        ),
        migrations.AddIndex(
            model_name="pathologyspecimen",
            index=models.Index(
                fields=["case", "status"], name="idx_pathspec_case_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="pathologyspecimen",
            constraint=models.UniqueConstraint(
                fields=("case", "specimen_code"), name="uq_pathology_specimen_case_code"
            ),
        ),
        migrations.AddIndex(
            model_name="wholeslideimage",
            index=models.Index(
                fields=["specimen", "is_current"], name="idx_wsi_specimen_current"
            ),
        ),
        migrations.AddConstraint(
            model_name="wholeslideimage",
            constraint=models.UniqueConstraint(
                fields=("specimen", "slide_code", "version"),
                name="uq_wsi_specimen_slide_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="wholeslideimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("specimen", "slide_code"),
                name="uq_wsi_current_specimen_slide",
            ),
        ),
        migrations.AddConstraint(
            model_name="wholeslideimage",
            constraint=models.CheckConstraint(
                check=models.Q(("mpp__gt", 0), ("mpp__isnull", True), _connector="OR"),
                name="ck_wsi_mpp_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="pathologyworkitem",
            index=models.Index(
                fields=["status", "priority", "created_at"],
                name="idx_pathwork_status_priority",
            ),
        ),
        migrations.AddIndex(
            model_name="pathologyworkitem",
            index=models.Index(
                fields=["assigned_to", "status"], name="idx_pathwork_assignee_status"
            ),
        ),
    ]
