# Generated by Django 5.0.6 on 2026-09-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pathology", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pathologyworkitem",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("WSI_UPLOAD", "WSI 등록"),
                    ("QUALITY_CHECK", "WSI 품질검증"),
                    ("ADEQUACY_ANALYSIS", "적정성 AI 분석"),
                    ("ADEQUACY_REVIEW", "적정성 전문의 판정"),
                    ("PATHOLOGY_ANALYSIS", "병리 AI 분석"),
                    ("PD_L1_REVIEW", "PD-L1 검토"),
                    ("DIAGNOSTIC_REVIEW", "병리 전문의 판독"),
                    ("REPORT_REVIEW", "병리 보고서 검토"),
                ],
                max_length=30,
            ),
        ),
    ]
