# Generated by Django 5.0.6 on 2026-09-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pathology", "0002_alter_pathologyworkitem_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="wholeslideimage",
            name="orthanc_instance_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="wholeslideimage",
            name="orthanc_series_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="wholeslideimage",
            name="series_instance_uid",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="wholeslideimage",
            name="sop_instance_uid",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="wholeslideimage",
            name="study_instance_uid",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
