# Generated by Django 5.0.6 on 2026-09-11 15:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_examination_order(apps, schema_editor):
    PathologyWorkItem = apps.get_model("pathology", "PathologyWorkItem")
    updates = []
    queryset = PathologyWorkItem.objects.select_related(
        "specimen__examination_order",
        "wsi__specimen__examination_order",
    )
    for work_item in queryset.iterator():
        specimen_order_id = (
            work_item.specimen.examination_order_id if work_item.specimen_id else None
        )
        wsi_order_id = (
            work_item.wsi.specimen.examination_order_id if work_item.wsi_id else None
        )
        candidates = {value for value in (specimen_order_id, wsi_order_id) if value}
        if len(candidates) != 1:
            continue
        order_id = candidates.pop()
        order = work_item.specimen.examination_order if specimen_order_id else work_item.wsi.specimen.examination_order
        if order.case_id != work_item.case_id:
            continue
        work_item.examination_order_id = order_id
        updates.append(work_item)
    if updates:
        PathologyWorkItem.objects.bulk_update(updates, ["examination_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_examinationorder_pathology_test_type"),
        ("pathology", "0003_wholeslideimage_orthanc_instance_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathologyworkitem",
            name="examination_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pathology_work_items",
                to="cases.examinationorder",
            ),
        ),
        migrations.RunPython(backfill_examination_order, migrations.RunPython.noop),
    ]
