import { expect, test } from "@playwright/test";
import { authenticateWithoutLogin } from "./fixtures/clinical-api";
import { installWorkflowAuditApi } from "./fixtures/workflow-audit-api";

test("candidates precede planning and saved R1 leads to confirmation then prescription", async ({ page }) => {
  const state = await installWorkflowAuditApi(page, "TREATMENT");
  await authenticateWithoutLogin(page);
  await page.goto("/respiratory/cases/case-treatment?openCurrentEvidence=1");
  await expect(page.getByRole("button", { name: "단계 처리 메뉴", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "처방 작성으로 이동 →" })).toHaveCount(0);
  await page.getByRole("button", { name: "치료계획 검토하기 →" }).click();
  const dialog = page.getByRole("dialog");
  await expect(dialog.getByRole("button", { name: /QA R1/ })).toBeVisible();
  await dialog.getByLabel("치료 유형").selectOption("TARGETED_THERAPY");
  await expect(dialog.getByRole("textbox", { name: "치료 계획", exact: true })).toBeDisabled();
  await expect(dialog.locator("details")).not.toHaveAttribute("open", "");
  const r1 = dialog.getByRole("button", { name: /QA R1/ });
  const r2 = dialog.getByRole("button", { name: /QA R2/ });
  await expect(r1).toBeVisible();
  await expect(r2).toBeVisible();
  const candidateBox = await r1.boundingBox();
  const planBox = await dialog.getByRole("textbox", { name: "치료 계획", exact: true }).boundingBox();
  expect(candidateBox!.y).toBeLessThan(planBox!.y);
  await r1.click();
  await expect(dialog.getByRole("textbox", { name: "치료 계획", exact: true })).toBeEnabled();
  await expect(dialog.locator("details")).not.toHaveAttribute("open", "");
  await expect(r1).toHaveAttribute("aria-pressed", "true");
  await expect(dialog.getByText("선택된 Regimen: R1 QA R1", { exact: true })).toBeVisible();
  await page.screenshot({ path: test.info().outputPath("candidate-selected.png") });
  await dialog.getByRole("textbox", { name: "치료 계획", exact: true }).fill("QA treatment plan");
  await dialog.locator("summary").click();
  await dialog.getByRole("textbox", { name: "결정 근거 (선택)", exact: true }).fill("QA saved rationale");
  await dialog.getByRole("button", { name: "임시 저장", exact: true }).click();
  await expect.poll(() => state.decision?.selected_regimen).toBe("R1");
  expect(state.decision?.decision_status).toBe("DRAFT");
  expect(state.case.current_stage).toBe("TREATMENT");
  await expect(dialog.getByRole("textbox", { name: "치료 계획", exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole("button", { name: "치료계획 계속 작성 →" }).click();
  await expect(r1).toHaveAttribute("aria-pressed", "true");
  await expect(dialog.getByRole("textbox", { name: "치료 계획", exact: true })).toHaveValue("QA treatment plan");
  await expect(dialog.locator("details")).not.toHaveAttribute("open", "");
  await expect(dialog.locator("summary")).toContainText("작성됨");
  await dialog.locator("summary").click();
  await expect(dialog.getByRole("textbox", { name: "결정 근거 (선택)", exact: true })).toHaveValue("QA saved rationale");
  await dialog.getByRole("button", { name: "저장하고 다음 단계", exact: true }).click();
  await expect(dialog.getByRole("heading", { name: "AI 치료 소견" })).toBeVisible();
  await expect(dialog.locator("button.bg-blue-600")).toHaveCount(1);
  await expect(dialog.getByRole("button", { name: "의료진 소견 저장", exact: true })).toHaveClass(/bg-white/);
  await dialog.getByRole("button", { name: "치료계획 확정", exact: true }).click();
  await expect.poll(() => state.decision?.decision_status).toBe("CONFIRMED");
  const confirmCount = () => state.writes.filter(write => write.path.endsWith("/treatment-decision/confirm/")).length;
  expect(confirmCount()).toBe(1);
  await page.getByRole("button", { name: "확정된 치료계획 보기" }).click();
  await expect(dialog.getByRole("textbox", { name: "치료 계획", exact: true })).toHaveCount(0);
  await expect(dialog.getByRole("button", { name: "치료계획 확정", exact: true })).toHaveCount(0);
  await expect(dialog.getByRole("textbox", { name: "호흡기내과 소견", exact: true })).toBeDisabled();
  await dialog.getByRole("button", { name: "닫기", exact: true }).click();
  await page.getByRole("button", { name: "처방 작성으로 이동 →" }).click();
  await expect(page.getByRole("button", { name: "처방 · 안전성", exact: true })).toHaveAttribute("aria-pressed", "true");
  expect(confirmCount()).toBe(1);
  expect(state.candidateCalls).toBeGreaterThan(1);
});

test("zero candidates explains unresolved EGFR and cannot confirm drug treatment", async ({ page }) => {
  const state = await installWorkflowAuditApi(page, "TREATMENT");
  state.candidates.splice(0);
  state.gene.result_detail.gene.findings[0].alteration_code = null;
  await authenticateWithoutLogin(page);
  await page.goto("/respiratory/cases/case-treatment?openCurrentEvidence=1");
  await page.getByRole("button", { name: "치료계획 검토하기 →" }).click();
  const dialog = page.getByRole("dialog");
  await expect(dialog.getByText(/EGFR.*변이/)).toBeVisible();
  await expect(dialog.getByRole("group", { name: "Regimen 후보" }).getByRole("button")).toHaveCount(0);
  await dialog.getByLabel("치료 유형").selectOption("TARGETED_THERAPY");
  await expect(dialog.getByRole("textbox", { name: "치료 계획", exact: true })).toBeDisabled();
  await expect(dialog.getByText("Regimen을 선택해주세요", { exact: true })).toHaveCount(0);
  await expect(dialog.getByText("조직/유전자 최종 검토에서 상세 변이를 확인해주세요.")).toBeVisible();
  await expect(dialog.locator("details")).not.toHaveAttribute("open", "");
  await dialog.locator("summary").click();
  await expect(dialog.locator("details")).not.toHaveAttribute("open", "");
  await expect(dialog.getByRole("button", { name: "저장하고 다음 단계", exact: true })).toBeDisabled();
  await expect(dialog.getByRole("button", { name: "치료계획 확정", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "처방 작성으로 이동 →" })).toHaveCount(0);
  await page.screenshot({ path: test.info().outputPath("zero-candidates.png") });
  expect(state.writes).toEqual([]);
  expect(state.case.current_stage).toBe("TREATMENT");
});

for (const type of ["SURGERY", "RADIATION", "OBSERVATION"]) {
  test(`${type} saves and confirms without a regimen or drug prescription CTA`, async ({ page }) => {
    const state = await installWorkflowAuditApi(page, "TREATMENT");
    state.candidates.splice(0);
    await page.route("**/treatment-decision/", async route => {
      if (route.request().method() !== "POST") return route.fallback();
      const body = route.request().postDataJSON();
      expect(body.selected_regimen).toBeNull();
      state.writes.push({ path: new URL(route.request().url()).pathname, body });
      state.decision = { id: "non-drug", ...body, selected_regimen_detail: null, requires_prescription: false, decision_status: "DRAFT" };
      return route.fulfill({ contentType: "application/json", body: JSON.stringify(state.decision) });
    });
    await authenticateWithoutLogin(page);
    await page.goto("/respiratory/cases/case-treatment?openCurrentEvidence=1");
    await page.getByRole("button", { name: "치료계획 검토하기 →" }).click();
    const dialog = page.getByRole("dialog");
    await dialog.getByLabel("치료 유형").selectOption(type);
    await expect(dialog.getByText("선택한 비약물 치료는 Regimen과 약물 처방이 필요하지 않습니다.")).toBeVisible();
    await expect(dialog.getByText("Regimen을 선택해주세요", { exact: true })).toHaveCount(0);
    await dialog.getByRole("textbox", { name: "치료 계획", exact: true }).fill(`QA ${type} plan`);
    await dialog.getByRole("button", { name: "저장하고 다음 단계", exact: true }).click();
    await dialog.getByRole("button", { name: "치료계획 확정", exact: true }).click();
    await expect(page.getByRole("button", { name: "확정된 치료계획 보기" })).toBeVisible();
    await expect(page.getByRole("button", { name: "처방 작성으로 이동 →" })).toHaveCount(0);
    expect(state.decision).toMatchObject({ treatment_type: type, selected_regimen: null, requires_prescription: false, decision_status: "CONFIRMED" });
    expect(state.writes.filter(write => write.path.endsWith("/treatment-decision/confirm/"))).toHaveLength(1);
  });
}
