# Generated by Django 5.0.6 on 2026-09-17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorWeeklyAvailability",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False, editable=False, default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weekday", models.PositiveSmallIntegerField(choices=[(0, "Monday"), (1, "Tuesday"), (2, "Wednesday"), (3, "Thursday"), (4, "Friday"), (5, "Saturday"), (6, "Sunday")])),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_minutes", models.PositiveSmallIntegerField(default=30)),
                ("enabled", models.BooleanField(default=True)),
                ("doctor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="weekly_availabilities", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "doctor_weekly_availabilities", "ordering": ["weekday", "start_time", "id"]},
        ),
        migrations.AddConstraint(model_name="doctorweeklyavailability", constraint=models.CheckConstraint(check=models.Q(("end_time__gt", models.F("start_time"))), name="ck_docweeklyavail_end_gt_start")),
        migrations.AddConstraint(model_name="doctorweeklyavailability", constraint=models.CheckConstraint(check=models.Q(("slot_minutes__gt", 0)), name="ck_docweeklyavail_slot_positive")),
        migrations.AddConstraint(model_name="doctorweeklyavailability", constraint=models.UniqueConstraint(fields=("doctor", "weekday", "start_time", "end_time"), name="uq_docweeklyavail_interval")),
    ]
