# Generated by Django 5.0.6 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("scheduling", "0002_doctorweeklyavailability")]

    operations = [
        migrations.AddConstraint(
            model_name="doctorweeklyavailability",
            constraint=models.CheckConstraint(
                check=models.Q(("slot_minutes", 30)),
                name="ck_docweeklyavail_slot_30_minutes",
            ),
        ),
    ]
