# Generated by Django 5.0.6 on 2026-09-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [("scheduling", "0003_doctorweeklyavailability_slot_30_minutes")]

    operations = [
        migrations.CreateModel(
            name="DoctorSchedulingPreference",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False, editable=False, default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slot_capacity", models.PositiveSmallIntegerField(default=5)),
                ("doctor", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="scheduling_preference", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "doctor_scheduling_preferences"},
        ),
        migrations.AddConstraint(
            model_name="doctorschedulingpreference",
            constraint=models.CheckConstraint(check=models.Q(("slot_capacity__gt", 0)), name="ck_docschedulepref_slot_capacity_positive"),
        ),
    ]
