"use client";
import { useEffect, useState } from "react";
import { API_BASE_URL } from "../../_lib/respiratory-api";
import { useRespiratoryAuth } from "../../_components/respiratory-auth-provider";
import { useRespiratoryToast } from "../../_components/respiratory-toast-provider";

type Recipient = { id: string; name: string; department: string; role: string };
type Consultation = { id: string; recipient_name?: string | null; question: string; priority: string; status: string; response_note?: string | null; responded_at?: string | null; created_at: string };
const statusLabel: Record<string, string> = { REQUESTED: "요청됨", ACKNOWLEDGED: "확인됨", RESPONDED: "회신됨", CANCELLED: "취소됨" };
export function CaseConsultationRequest({ caseId }: { caseId: string }) {
  const { authorizedFetch } = useRespiratoryAuth(); const { showToast } = useRespiratoryToast(); const [open, setOpen] = useState(false); const [recipients, setRecipients] = useState<Recipient[]>([]); const [items, setItems] = useState<Consultation[]>([]); const [recipientId, setRecipientId] = useState(""); const [question, setQuestion] = useState(""); const [priority, setPriority] = useState("NORMAL"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = async () => { const r = await authorizedFetch(`${API_BASE_URL}/api/doctor/cases/${caseId}/consultations/`); if (r.ok) { const d = await r.json(); setItems(Array.isArray(d) ? d : []); } };
  useEffect(() => { const initial = window.setTimeout(() => void load(), 0); const timer = window.setInterval(() => void load(), 30000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [caseId]);
  useEffect(() => { if (!open) return; void authorizedFetch(`${API_BASE_URL}/api/chat/cases/${caseId}/recipients/`).then(async (r) => r.ok ? r.json() : []).then((d: unknown) => setRecipients(Array.isArray(d) ? (d as Recipient[]).filter((x) => x.department === "PULMONOLOGY" || x.department === "호흡기내과") : [])); }, [authorizedFetch, caseId, open]);
  const submit = async () => { setBusy(true); setError(""); try { const r = await authorizedFetch(`${API_BASE_URL}/api/doctor/cases/${caseId}/consultations/`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recipient_user_id: recipientId || null, question, priority }) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(typeof d.detail === "string" ? d.detail : "협진 요청에 실패했습니다."); setQuestion(""); setRecipientId(""); setOpen(false); showToast("호흡기내과 협진 요청을 전송했습니다."); await load(); } catch (e) { setError(e instanceof Error ? e.message : "협진 요청에 실패했습니다."); } finally { setBusy(false); } };
  return <><button type="button" onClick={() => setOpen(true)} className="rounded-md border border-violet-200 bg-violet-50 px-2.5 py-1.5 text-[10px] font-semibold text-violet-800">협진 요청{items.length ? ` · ${items.length}` : ""}</button>{open && <div role="presentation" className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/45 p-4"><section role="dialog" aria-modal="true" className="max-h-[calc(100vh-2rem)] w-full max-w-lg overflow-y-auto rounded-xl bg-white p-5 shadow-2xl"><h2 className="text-base font-bold">호흡기내과 협진 요청</h2><p className="mt-1 text-xs text-slate-500">수신 의료진을 비워두면 호흡기내과 전체에 요청됩니다.</p><div className="mt-4 grid grid-cols-2 gap-3"><select value={recipientId} onChange={(e) => setRecipientId(e.target.value)} className="rounded border border-slate-300 p-2 text-sm"><option value="">호흡기내과 전체</option>{recipients.map((x) => <option key={x.id} value={x.id}>{x.name} · {x.role}</option>)}</select><select value={priority} onChange={(e) => setPriority(e.target.value)} className="rounded border border-slate-300 p-2 text-sm"><option value="NORMAL">일반</option><option value="URGENT">긴급</option></select></div><textarea value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="요청 내용을 입력하세요." className="mt-3 h-24 w-full resize-none rounded border border-slate-300 p-2 text-sm" />{error && <p role="alert" className="mt-2 text-xs text-rose-700">{error}</p>}<div className="mt-3 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded border px-3 py-2 text-xs">닫기</button><button type="button" disabled={busy || !question.trim()} onClick={() => void submit()} className="rounded bg-violet-600 px-3 py-2 text-xs font-semibold text-white disabled:bg-slate-300">{busy ? "전송 중" : "전송"}</button></div><div className="mt-5 border-t pt-3"><p className="text-xs font-bold text-slate-700">최근 협진 요청</p>{items.length ? items.slice(0, 5).map((x) => <article key={x.id} className="mt-2 rounded border border-slate-100 bg-slate-50 p-2 text-[10px]"><div className="flex justify-between"><span className="font-semibold text-violet-700">{statusLabel[x.status] ?? x.status}</span><span>{x.recipient_name || "호흡기내과 전체"}</span></div><p className="mt-1 text-slate-700">{x.question}</p>{x.response_note && <p className="mt-1 border-t pt-1 text-emerald-700">회신: {x.response_note}</p>}</article>) : <p className="mt-2 text-xs text-slate-400">요청 이력이 없습니다.</p>}</div></section></div>}</>;
}
