"use client";

import { useEffect, useId, useRef, useState } from "react";

import { ensureCornerstoneInitialized } from "../../../radiology/_lib/cornerstone-init";

type AuthorizedFetch = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
type Asset = { id: string; workflow_stage: string; image_type: string; file_format: string; status: string };
const message = (body: unknown, fallback: string) => body && typeof body === "object" && "detail" in body && typeof body.detail === "string" ? body.detail : fallback;
const sopUid = (row: unknown) => row && typeof row === "object" && "00080018" in row && row["00080018"] && typeof row["00080018"] === "object" && "Value" in row["00080018"] && Array.isArray(row["00080018"].Value) && typeof row["00080018"].Value[0] === "string" ? row["00080018"].Value[0] : null;

export function CaseDicomEvidence({ apiBaseUrl, authorizedFetch, caseId, stage }: { apiBaseUrl: string; authorizedFetch: AuthorizedFetch; caseId: string; stage: string }) {
  const elementRef = useRef<HTMLDivElement>(null); const reactId = useId();
  const [asset, setAsset] = useState<Asset | null>(null); const [uids, setUids] = useState<string[]>([]); const [index, setIndex] = useState(0); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { const controller = new AbortController(); void (async () => { setLoading(true); setError(""); try { const response = await authorizedFetch(`${apiBaseUrl}/api/doctor/cases/${caseId}/image-assets/`, { signal: controller.signal }); const payload: unknown = await response.json(); if (!response.ok) throw new Error(message(payload, "영상 목록을 불러오지 못했습니다.")); const selected = (Array.isArray(payload) ? payload as Asset[] : []).find((item) => item.workflow_stage === stage && item.status === "READY" && (item.image_type === "CT" || item.image_type === "PET")); if (!selected) throw new Error("조회 가능한 DICOM Series가 없습니다."); const instances = await authorizedFetch(`${apiBaseUrl}/api/doctor/cases/${caseId}/image-assets/${selected.id}/dicom-web/instances/`, { signal: controller.signal }); const instancePayload: unknown = await instances.json(); if (!instances.ok) throw new Error(message(instancePayload, "DICOM instance 목록을 불러오지 못했습니다.")); const nextUids = (Array.isArray(instancePayload) ? instancePayload : []).map(sopUid).filter((uid): uid is string => Boolean(uid)); if (!nextUids.length) throw new Error("DICOM instance가 없습니다."); if (!controller.signal.aborted) { setAsset(selected); setUids(nextUids); setIndex(Math.floor(nextUids.length / 2)); setLoading(false); } } catch (cause) { if (!controller.signal.aborted) { setError(cause instanceof Error ? cause.message : "DICOM 조회 중 오류가 발생했습니다."); setLoading(false); } } })(); return () => controller.abort(); }, [apiBaseUrl, authorizedFetch, caseId, stage]);
  useEffect(() => { if (!asset || !uids[index] || !elementRef.current) return; let cancelled = false; let engine: import("@cornerstonejs/core").RenderingEngine | null = null; void (async () => { try { const response = await authorizedFetch(`${apiBaseUrl}/api/doctor/cases/${caseId}/image-assets/${asset.id}/dicom-web/instances/${uids[index]}/`, { headers: { Accept: "application/dicom" } }); if (!response.ok) throw new Error("원본 DICOM을 불러오지 못했습니다."); const blob = await response.blob(); const { core, dicomImageLoader } = await ensureCornerstoneInitialized(); if (cancelled || !elementRef.current) return; const imageId = dicomImageLoader.wadouri.fileManager.add(new File([blob], `${uids[index]}.dcm`, { type: "application/dicom" })); engine = new core.RenderingEngine(`respiratory-dicom-engine-${reactId}`); const viewportId = `respiratory-dicom-viewport-${reactId}`; engine.enableElement({ viewportId, type: core.Enums.ViewportType.STACK, element: elementRef.current }); const viewport = engine.getViewport(viewportId) as InstanceType<typeof core.StackViewport>; await viewport.setStack([imageId]); viewport.render(); } catch (cause) { if (!cancelled) setError(cause instanceof Error ? cause.message : "원본 DICOM을 표시하지 못했습니다."); } })(); return () => { cancelled = true; engine?.destroy(); }; }, [apiBaseUrl, asset, authorizedFetch, caseId, index, reactId, uids]);
  return <section className="overflow-hidden rounded-lg border border-slate-200 bg-white"><header className="flex items-center justify-between border-b border-slate-200 px-4 py-3"><div><p className="text-[10px] font-semibold text-blue-600">원본 근거 · DICOM</p><h2 className="mt-0.5 text-sm font-bold text-slate-800">{stage === "PET_CT_TNM" ? "PET-CT/TNM" : "흉부 CT"} 원본 영상</h2></div><span className="text-xs text-slate-400">{uids.length ? `${index + 1} / ${uids.length}` : ""}</span></header><div className="relative min-h-[420px] bg-black"><div ref={elementRef} tabIndex={0} onKeyDown={(event) => { if (event.key === "ArrowLeft") { event.preventDefault(); setIndex((value) => Math.max(0, value - 1)); } if (event.key === "ArrowRight") { event.preventDefault(); setIndex((value) => Math.min(uids.length - 1, value + 1)); } }} className="absolute inset-0 outline-none focus:ring-2 focus:ring-inset focus:ring-blue-400" aria-label="DICOM 원본 영상 뷰어. 좌우 화살표로 슬라이스 이동" />{loading && <p role="status" className="grid min-h-[420px] place-items-center text-sm text-slate-300">DICOM Series를 불러오는 중입니다.</p>}{!loading && error && <p role="alert" className="grid min-h-[420px] place-items-center px-8 text-center text-sm text-rose-200">{error}</p>}</div>{uids.length > 1 && <footer className="flex items-center justify-between gap-3 px-4 py-2"><span className="hidden text-[10px] text-slate-400 sm:block">뷰어 선택 후 ← / → 키로 이동</span><button type="button" disabled={index === 0} onClick={() => setIndex((value) => value - 1)} className="rounded border px-3 py-1 text-xs disabled:text-slate-300">이전 슬라이스</button><input aria-label="DICOM 슬라이스" type="range" min={0} max={uids.length - 1} value={index} onChange={(event) => setIndex(Number(event.target.value))} className="flex-1" /><button type="button" disabled={index === uids.length - 1} onClick={() => setIndex((value) => value + 1)} className="rounded border px-3 py-1 text-xs disabled:text-slate-300">다음 슬라이스</button></footer>}</section>;
}
