"use client";
import { useState } from "react";
import type { AuthorizedFetch } from "./treatment-prescription-types";
type Product = { item_seq: string; item_name?: string; entp_name?: string; item_ingr_name?: string; cancel_date?: string | null; approval_status: string };
export function MfdsProductSelector({ ingredientName, selectedItemSeq, apiBaseUrl, authorizedFetch, onSelect }: { ingredientName?: string | null; selectedItemSeq?: string | null; apiBaseUrl: string; authorizedFetch: AuthorizedFetch; onSelect: (itemSeq: string) => Promise<void> }) {
 const [products,setProducts]=useState<Product[]>([]); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const search=async()=>{if(!ingredientName?.trim()){setError("성분명이 없어 제품을 검색할 수 없습니다.");return;} setOpen(true);setBusy(true);setError("");try{const r=await authorizedFetch(`${apiBaseUrl}/api/doctor/cases/mfds-products/?ingredient_name=${encodeURIComponent(ingredientName.trim())}`);const d=await r.json();if(!r.ok)throw new Error(d.detail||"MFDS 제품 검색에 실패했습니다.");setProducts(d.products??[]);}catch(e){setError(e instanceof Error?e.message:"MFDS 제품 검색에 실패했습니다.");}finally{setBusy(false);}};
 return <div className="mt-1 space-y-1"><div>{selectedItemSeq?`ITEM_SEQ ${selectedItemSeq}`:"제품 미선택"} <button type="button" onClick={()=>void search()} className="ml-1 rounded border px-2 py-1 text-xs">제품 선택</button></div>{open&&<div className="space-y-1 rounded border bg-slate-50 p-2">{busy&&<p>제품 검색 중...</p>}{error&&<p role="alert" className="text-rose-600">{error}</p>}{!busy&&!error&&products.length===0&&<p>검색 결과가 없습니다.</p>}{products.map(p=><button type="button" key={p.item_seq} onClick={()=>void onSelect(p.item_seq)} className="block w-full rounded border bg-white p-2 text-left"><div className="font-medium">{p.item_name||"제품명 없음"} · {p.entp_name||"업체명 없음"}</div><div>{p.item_ingr_name||"성분 정보 없음"}</div><div>ITEM_SEQ: {p.item_seq} · {p.approval_status==="APPROVED_OR_ACTIVE"?"허가/유효 가능":`취하/취소 ${p.cancel_date||""}`}</div></button>)}</div>}</div>;
}
