"use client";
import { useCallback, useEffect, useState } from "react";
import { MfdsProductSelector } from "./mfds-product-selector";
import type { AuthorizedFetch, Prescription } from "./treatment-prescription-types";
export function PrescriptionPanel({ caseId, apiBaseUrl, authorizedFetch, refreshKey = 0 }: { caseId: string; apiBaseUrl: string; authorizedFetch: AuthorizedFetch; refreshKey?: number }) {
 const [prescriptions,setPrescriptions]=useState<Prescription[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const r=await authorizedFetch(`${apiBaseUrl}/api/doctor/cases/${caseId}/prescriptions/`);const d=await r.json();if(!r.ok)throw new Error(d.detail||"Prescription request failed.");setPrescriptions(d);}catch(e){setError(e instanceof Error?e.message:"Prescription request failed.");}finally{setLoading(false);}},[apiBaseUrl,authorizedFetch,caseId]);
 useEffect(()=>{void load();},[load,refreshKey]);
 if(loading)return <section className="rounded-lg bg-white p-4 text-sm">처방 조회 중...</section>;
 return <section className="space-y-4 rounded-lg border border-slate-200 bg-white p-4">{error&&<p role="alert" className="text-xs text-rose-600">{error}</p>}{prescriptions.map(rx=><article key={rx.id} className="rounded border p-3"><strong>{rx.regimen_detail?.regimen_name??"Regimen"}</strong><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><tbody>{rx.items.map(item=><tr key={item.id} className="border-t"><td className="py-2">{item.drug_name}<MfdsProductSelector ingredientName={item.ingredient_name??item.drug_name} selectedItemSeq={item.mfds_item_seq} apiBaseUrl={apiBaseUrl} authorizedFetch={authorizedFetch} onSelect={async seq=>{const r=await authorizedFetch(`${apiBaseUrl}/api/doctor/cases/${caseId}/prescriptions/${rx.id}/items/${item.id}/`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({mfds_item_seq:seq})});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.detail||"제품 저장에 실패했습니다.");}await load();}} /></td><td>{item.calculated_dose??"-"}</td><td>{item.final_dose??"-"} {item.unit??""}</td></tr>)}</tbody></table></div></article>)}</section>;
}
